import React,{useEffect,useState} from "react";
import {Pencil,Plus,RefreshCw,Trash2} from "lucide-react";
import PageHeader from "../components/PageHeader.jsx";
import EditMasterLink from "../components/EditMasterLink.jsx";
import DataTable from "../components/DataTable.jsx";
import StatusBadge from "../components/StatusBadge.jsx";
import {api} from "../lib/api.js";
import {getLookupEditId,isLookupCreate,notifyLookupCreated} from "../components/CreateLookupButton.jsx";

const blank={name:"",branchCode:"",address:"",pincode:"",district:"",state:"",status:"ACTIVE"};
const digits=v=>String(v||"").replace(/\D/g,"").slice(0,6);
export default function BranchManagementPage(){
 const[rows,setRows]=useState([]),[info,setInfo]=useState({limit:0,used:0,remaining:0}),[form,setForm]=useState(blank),[show,setShow]=useState(false),[edit,setEdit]=useState(null),[msg,setMsg]=useState("");
 const load=async()=>{try{const d=await api("/access/branches");const loaded=Array.isArray(d)?d:(d.items||[]);setRows(loaded);setInfo(Array.isArray(d)?{limit:d.length,used:d.length,remaining:0}:d);return loaded}catch(e){setMsg(e.message)}};
 useEffect(()=>{(async()=>{const loaded=await load();const lookupEditId=getLookupEditId();if(lookupEditId){const row=(loaded||[]).find(r=>String(r._id)===String(lookupEditId));if(row)open(row);else setMsg("Selected branch could not be loaded for editing")}else if(isLookupCreate())open(null)})()},[]);
 const lookup=async raw=>{const p=digits(raw);setForm(f=>({...f,pincode:p}));if(p.length!==6)return;try{const r=await api(`/access/pincode-lookup/${p}`);setForm(f=>({...f,pincode:p,district:r.district||"",state:r.state||""}))}catch(e){setMsg(e.message)}};
 const open=r=>{setEdit(r||null);setForm(r?{...blank,...r}:blank);setShow(true);setMsg("")};
 const save=async()=>{try{if(!form.name.trim())throw new Error("Branch Name is required");const saved=await api(edit?`/access/branches/${edit._id}`:"/access/branches",{method:edit?"PUT":"POST",body:JSON.stringify(form)});setShow(false);setEdit(null);setForm(blank);await load();setMsg(edit?"Branch updated":"Branch created");if(isLookupCreate()||getLookupEditId())notifyLookupCreated("branch",{id:saved?._id||edit?._id,name:saved?.name||form.name})}catch(e){setMsg(e.message)}};
 const del=async r=>{if(!confirm(`Deactivate branch ${r.name}?`))return;try{await api(`/access/branches/${r._id}`,{method:"DELETE"});await load()}catch(e){setMsg(e.message)}};
 return <><PageHeader title="Branch Management" description={`Create company branches within the plan limit. ${info.used||0} of ${info.limit||0} branch slot(s) used.`} onAdd={()=>open(null)} addLabel="Create Branch"/>{msg&&<div className="resultBanner good">{msg}</div>}{show&&<section className="panel"><div className="sectionLabel">{edit?"Edit Branch":"Create Branch"}</div><div className="formGrid"><label>Branch Name *<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Branch Code<input value={form.branchCode} onChange={e=>setForm({...form,branchCode:e.target.value.toUpperCase()})}/></label><label>Pincode<input value={form.pincode} onChange={e=>lookup(e.target.value)} maxLength={6}/></label><label>District<input value={form.district} readOnly/></label><label>State<input value={form.state} readOnly/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></label><label className="span2">Address<textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></div><div className="formActions"><button className="btn ghost" onClick={()=>setShow(false)}>Cancel</button><button className="btn primary" onClick={save}>{edit?"Update":"Create"}</button></div></section>}<section className="panel"><div className="toolbar"><button className="btn ghost" onClick={load}><RefreshCw/>Refresh</button><span>Plan limit: {info.limit||0} • Used: {info.used||0} • Remaining: {info.remaining||0}</span></div><DataTable rows={rows} columns={[{key:"branchCode",label:"Code"},{key:"name",label:"Branch",render:r=><EditMasterLink onClick={()=>open(r)}>{r.name}</EditMasterLink>},{key:"pincode",label:"Pincode"},{key:"district",label:"District"},{key:"state",label:"State"},{key:"status",label:"Status",render:r=><StatusBadge value={r.status}/>},{key:"actions",label:"Actions",render:r=><div className="rowActions"><button onClick={()=>open(r)}><Pencil/></button><button className="danger" onClick={()=>del(r)}><Trash2/></button></div>}]} /></section></>;
}
