import React,{useEffect,useMemo,useRef,useState} from "react";
import { BadgeCheck,ChevronDown,ChevronRight,Download,Pencil,Power,RefreshCw,Search,Upload } from "lucide-react";
import PageHeader from "../components/PageHeader.jsx";
import EditMasterLink from "../components/EditMasterLink.jsx";
import DataTable from "../components/DataTable.jsx";
import { api } from "../lib/api.js";
import "../role-permissions.css";

const upper=v=>String(v||"").trim().toUpperCase().replace(/[^A-Z0-9]+/g,"_").replace(/^_|_$/g,"");
const blank={name:"",code:"",department:"",description:"",permissions:[],fieldAccess:{},workflowTransitions:{},status:"ACTIVE"};

export default function DesignationSecurityPage(){
 const[rows,setRows]=useState([]),[catalogue,setCatalogue]=useState({actions:[],groups:[]}),[form,setForm]=useState(blank),[show,setShow]=useState(false),[edit,setEdit]=useState(null),[expanded,setExpanded]=useState({}),[q,setQ]=useState(""),[listQ,setListQ]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);const fileRef=useRef();
 const load=async()=>{try{const[c,d]=await Promise.all([api("/access/permission-catalogue"),api("/access/designations")]);setCatalogue(c||{actions:[],groups:[]});setRows((Array.isArray(d)?d:[]).filter(r=>(r.apps||[]).includes("dms") || (r.permissions||[]).some(code=>String(code).startsWith("dms."))))}catch(e){setMsg(e.message)}};useEffect(()=>{load()},[]);
 const groups=useMemo(()=>{const needle=q.trim().toLowerCase();return (catalogue.groups||[]).filter(g=>g.app==="dms").map(g=>({...g,screens:(g.screens||[]).filter(s=>!needle||`${g.category} ${s.label}`.toLowerCase().includes(needle))})).filter(g=>g.screens.length)},[catalogue,q]);
 const known=useMemo(()=>{const out=new Set();for(const g of (catalogue.groups||[]).filter(x=>x.app==="dms"))for(const screen of g.screens||[])for(const action of screen.allowedActions||[])out.add(`${screen.key}.${action}`);return out},[catalogue]);
 const selected=useMemo(()=>new Set((form.permissions||[]).filter(code=>known.has(code))),[form.permissions,known]);
 const codesFor=(g,a=null)=>{const out=[];for(const s of g.screens||[])for(const x of s.allowedActions||[])if(!a||a===x)out.push(`${s.key}.${x}`);return out};
 const all=c=>c.length>0&&c.every(x=>selected.has(x)),some=c=>c.some(x=>selected.has(x));
 const setCodes=(codes,checked)=>{const next=new Set(selected);codes.forEach(x=>checked?next.add(x):next.delete(x));setForm(f=>({...f,permissions:[...next]}))};
 const open=r=>{setEdit(r||null);setForm(r?{...blank,...r,permissions:r.permissions||[],fieldAccess:r.fieldAccess||{},workflowTransitions:r.workflowTransitions||{}}:{...blank});setShow(true);setExpanded({});setQ("")};
 const save=async()=>{if(!form.name||!form.code)return setMsg("Designation name and code are required");setBusy(true);try{const payload={name:form.name,code:upper(form.code),department:form.department,description:form.description,permissions:[...selected],fieldAccess:form.fieldAccess,workflowTransitions:form.workflowTransitions,status:form.status};await api(edit?`/access/designations/${edit._id}`:"/access/designations",{method:edit?"PUT":"POST",body:JSON.stringify(payload)});setMsg(edit?"Designation updated":"Designation created");setShow(false);load()}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 const reset=async()=>{if(!confirm("Restore predefined designation templates?"))return;try{await api("/access/designations/reset-defaults",{method:"POST",body:"{}"});setMsg("Defaults restored");load()}catch(e){setMsg(e.message)}};
 const deactivate=async r=>{if(!confirm(`Deactivate ${r.name}?`))return;try{await api(`/access/designations/${r._id}`,{method:"DELETE"});setMsg("Designation deactivated");load()}catch(e){setMsg(e.message)}};
 const upload=async file=>{if(!file)return;const fd=new FormData();fd.append("file",file);setBusy(true);try{const r=await api("/access/designations/bulk-upload",{method:"POST",body:fd});setMsg(`${r.designations||0} designation(s) processed • ${r.invalid||0} invalid row(s)`);load()}catch(e){setMsg(e.message)}finally{setBusy(false);if(fileRef.current)fileRef.current.value=""}};
 const filtered=rows.filter(r=>`${r.name} ${r.code} ${r.department} ${r.description||""}`.toLowerCase().includes(listQ.toLowerCase()));
 return <>
  <PageHeader onAdd={()=>open(null)} addLabel="Create Designation"/>
  {msg&&<div className="resultBanner good">{msg}</div>}
  <section className="panel"><div className="toolbar"><a className="btn ghost" href="/templates/Designation_Permissions_Bulk_Upload.xlsx" download><Download size={15}/>Download XLS Template</a><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>upload(e.target.files?.[0])}/><button className="btn ghost" onClick={()=>fileRef.current?.click()} disabled={busy}><Upload size={15}/>Bulk Upload XLS</button><button className="btn ghost" onClick={reset}><RefreshCw size={15}/>Restore Defaults</button></div></section>
  {show&&<section className="panel editorPanel rpEditor">
   <div className="formTitle"><div><h3>{edit?"Edit":"Create"} Designation</h3><span>{selected.size} action permission(s) selected.</span></div><button className="btn ghost" onClick={()=>setShow(false)}>Close</button></div>
   <div className="formGrid"><label>Designation Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Code<input value={form.code} onChange={e=>setForm({...form,code:upper(e.target.value)})}/></label><label>Department<input value={form.department||""} onChange={e=>setForm({...form,department:e.target.value})}/></label><label>Status<select value={form.status||"ACTIVE"} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></label><label className="wideField">Description<input value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})}/></label></div>
   <div className="rpPermissionToolbar"><div className="searchBox"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search permission screens..."/></div><div className="rpQuick"><button onClick={()=>{const c=groups.flatMap(g=>codesFor(g));setCodes(c,true)}}>Select Visible</button><button onClick={()=>{const c=groups.flatMap(g=>codesFor(g));setCodes(c,false)}}>Deselect Visible</button></div><span className="rpCount">{selected.size} selected</span></div>
   <div className="rpMatrix">{groups.map(g=>{const id=`${g.app}:${g.category}`,open=!!expanded[id],gc=codesFor(g);return <div className="rpGroup" key={id}><div className="rpGroupHead"><button className="rpExpand" onClick={()=>setExpanded(x=>({...x,[id]:!x[id]}))}>{open?<ChevronDown/>:<ChevronRight/>}</button><div className="rpGroupTitle" onClick={()=>setExpanded(x=>({...x,[id]:!x[id]}))}><strong>{g.category}</strong><span>{g.screens.length} screens</span></div><label className="rpSelectAll"><input type="checkbox" checked={all(gc)} ref={el=>{if(el)el.indeterminate=!all(gc)&&some(gc)}} onChange={e=>setCodes(gc,e.target.checked)}/><span>Select All</span></label></div>{open&&<div className="rpTableWrap"><table className="rpTable"><thead><tr><th className="rpScreenCol">Screen</th>{(catalogue.actions||[]).map(a=>{const c=codesFor(g,a.key);return <th key={a.key}><span>{a.label}</span>{c.length>0&&<input type="checkbox" checked={all(c)} ref={el=>{if(el)el.indeterminate=!all(c)&&some(c)}} onChange={e=>setCodes(c,e.target.checked)}/>}</th>})}</tr></thead><tbody>{g.screens.map(screen=><tr key={screen.key}><td className="rpScreenCol"><strong>{screen.label}</strong></td>{(catalogue.actions||[]).map(a=>{const allowed=(screen.allowedActions||[]).includes(a.key),code=`${screen.key}.${a.key}`;return <td key={a.key} className={!allowed?"rpDisabled":""}><input type="checkbox" disabled={!allowed} checked={allowed&&selected.has(code)} onChange={e=>setCodes([code],e.target.checked)}/></td>})}</tr>)}</tbody></table></div>}</div>})}</div>
   <div className="rpSectionHead"><div><strong>Advanced security (JSON)</strong><span>Optional field/workflow restrictions can remain configured here.</span></div></div><div className="formGrid"><label className="wideField">Field Access JSON<textarea rows="5" value={JSON.stringify(form.fieldAccess||{},null,2)} onChange={e=>{try{setForm({...form,fieldAccess:JSON.parse(e.target.value)})}catch{}}}/></label><label className="wideField">Workflow Transitions JSON<textarea rows="5" value={JSON.stringify(form.workflowTransitions||{},null,2)} onChange={e=>{try{setForm({...form,workflowTransitions:JSON.parse(e.target.value)})}catch{}}}/></label></div>
   <div className="formActions"><button className="btn ghost" onClick={()=>setShow(false)}>Cancel</button><button className="btn primary" disabled={busy||!form.name||!form.code} onClick={save}>Save Designation</button></div>
  </section>}
  <section className="panel"><div className="toolbar"><div className="searchBox"><Search/><input value={listQ} onChange={e=>setListQ(e.target.value)} placeholder="Search designations..."/></div><div className="recordCount"><BadgeCheck size={15}/>{filtered.length} designation(s)</div></div><DataTable rows={filtered} columns={[{key:"name",label:"Designation",render:r=><div><EditMasterLink onClick={()=>open(r)}>{r.name}</EditMasterLink><small style={{display:"block",color:"#8b8fa3"}}>{r.description}</small></div>},{key:"department",label:"Department"},{key:"permissions",label:"Permissions",render:r=>(r.permissions||[]).length},{key:"status",label:"Status",status:true},{key:"actions",label:"Actions",render:r=><div className="rowActions"><button onClick={()=>open(r)}><Pencil/></button><button title="Deactivate" className="danger" onClick={()=>deactivate(r)}><Power/></button></div>} ]}/></section>
 </>;
}
