import React,{useEffect,useMemo,useState} from "react";
import { Pencil,Trash2,Search,RefreshCw,X } from "lucide-react";
import PageHeader from "../components/PageHeader.jsx";
import DataTable from "../components/DataTable.jsx";
import BulkTools from "../components/BulkTools.jsx";
import StatusBadge from "../components/StatusBadge.jsx";
import EditMasterLink from "../components/EditMasterLink.jsx";
import {getLookupEditId,isLookupCreate,notifyLookupCreated} from "../components/CreateLookupButton.jsx";
import { api } from "../lib/api.js";

const configs={
 units:{title:"Units / UQC",description:"Company units used by products, stock, purchase and sales invoices.",endpoint:"/catalog/units",blank:{code:"",name:"",uqc:"",decimals:0,status:"ACTIVE"},fields:[{key:"code",label:"Code",example:"PCS",noBulkEdit:true},{key:"name",label:"Unit Name",example:"Pieces"},{key:"uqc",label:"UQC",example:"PCS"},{key:"decimals",label:"Decimals",type:"number",example:"0"},{key:"status",label:"Status",type:"select",options:["ACTIVE","INACTIVE"],example:"ACTIVE"}]},
 grades:{title:"Customer Grades",description:"Customer grade and grade discount used automatically in DMS sales invoices and price lists.",endpoint:"/catalog/grades",blank:{code:"",name:"",discountPct:0,description:"",status:"ACTIVE"},fields:[{key:"code",label:"Grade Code",example:"A",noBulkEdit:true},{key:"name",label:"Grade Name",example:"Grade A"},{key:"discountPct",label:"Grade Discount %",type:"number",example:"5"},{key:"description",label:"Description",example:"Premium customers"},{key:"status",label:"Status",type:"select",options:["ACTIVE","INACTIVE"],example:"ACTIVE"}]},
 categories:{title:"Product Categories",description:"Company category and sub-category master used by Product Creation and reporting.",endpoint:"/catalog/categories",blank:{code:"",name:"",subcategories:"",status:"ACTIVE"},fields:[{key:"code",label:"Code",example:"CUTLERY",noBulkEdit:true},{key:"name",label:"Category",example:"Cutlery"},{key:"subcategories",label:"Sub Categories",example:"Spoon,Fork,Knife"},{key:"status",label:"Status",type:"select",options:["ACTIVE","INACTIVE"],example:"ACTIVE"}]}
};

export default function DmsCatalogPage({type="units"}){
 const c=configs[type];const[rows,setRows]=useState([]),[q,setQ]=useState(""),[page,setPage]=useState(1),[meta,setMeta]=useState({page:1,pages:1,total:0}),[selected,setSelected]=useState([]),[show,setShow]=useState(false),[edit,setEdit]=useState(null),[form,setForm]=useState(c.blank),[msg,setMsg]=useState("");
 const load=async(next=page)=>{try{const d=await api(`${c.endpoint}?q=${encodeURIComponent(q)}&page=${next}&limit=50`);const loaded=d.items||[];setRows(loaded);setMeta(d.meta||{page:next,pages:1,total:loaded.length});setPage(d.meta?.page||next);return loaded}catch(e){setMsg(e.message);return []}};
 useEffect(()=>{setForm(c.blank);setSelected([]);load(1)},[type]);
 useEffect(()=>{(async()=>{const lookupEditId=getLookupEditId();if(lookupEditId){const d=await api(`${c.endpoint}?page=1&limit=500`).catch(()=>({items:[]}));const row=(d.items||[]).find(r=>String(r._id)===String(lookupEditId));if(row)open(row);else setMsg("Selected record could not be loaded for editing")}else if(isLookupCreate())open(null)})()},[type]);
 const viewRows=useMemo(()=>type==="categories"?rows.map(r=>({...r,subcategoriesText:(r.subcategories||[]).map(x=>x.name).join(", ")})):rows,[rows,type]);
 const open=r=>{setEdit(r||null);setForm(r?{...c.blank,...r,subcategories:type==="categories"?(r.subcategories||[]).map(x=>x.name).join(", "):r.subcategories}:c.blank);setShow(true)};
 const save=async()=>{try{const body={...form};if(type==="categories")body.subcategories=String(form.subcategories||"").split(/[,;|]/).map((name,i)=>({code:`${String(form.code||"CAT").toUpperCase()}-${i+1}`,name:name.trim(),status:"ACTIVE"})).filter(x=>x.name);const saved=await api(edit?`${c.endpoint}/${edit._id}`:c.endpoint,{method:edit?"PUT":"POST",body:JSON.stringify(body)});setMsg(edit?"Updated":"Created");setShow(false);await load();if(isLookupCreate()||getLookupEditId())notifyLookupCreated(type==="categories"?"category":type==="grades"?"grade":"unit",{id:saved?._id||edit?._id,code:saved?.code||form.code,name:saved?.name||form.name})}catch(e){setMsg(e.message)}};
 const del=async r=>{if(!confirm(`Deactivate ${r.name||r.code}?`))return;try{await api(`${c.endpoint}/${r._id}`,{method:"DELETE"});setMsg("Deactivated");await load()}catch(e){setMsg(e.message)}};
 const toggle=id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);const toggleAll=(checked,ids)=>setSelected(s=>checked?[...new Set([...s,...ids])]:s.filter(x=>!ids.includes(x)));
 const cols=type==="units"?[{key:"code",label:"Code"},{key:"name",label:"Unit",render:r=><EditMasterLink onClick={()=>open(r)}>{r.name}</EditMasterLink>},{key:"uqc",label:"UQC"},{key:"decimals",label:"Decimals"}]:type==="grades"?[{key:"code",label:"Grade"},{key:"name",label:"Name",render:r=><EditMasterLink onClick={()=>open(r)}>{r.name}</EditMasterLink>},{key:"discountPct",label:"Discount",render:r=>`${Number(r.discountPct||0)}%`},{key:"description",label:"Description"}]:[{key:"code",label:"Code"},{key:"name",label:"Category",render:r=><EditMasterLink onClick={()=>open(r)}>{r.name}</EditMasterLink>},{key:"subcategoriesText",label:"Sub Categories"}];
 return <>
  <PageHeader title={c.title} description={c.description} onAdd={()=>open(null)} addLabel={`Add ${type==="grades"?"Grade":type==="categories"?"Category":"Unit"}`}/>
  {msg&&<div className="resultBanner good">{msg}</div>}
  <BulkTools endpoint={c.endpoint} fields={c.fields} editFields={c.fields.filter(f=>!f.noBulkEdit)} selectedIds={selected} onClear={()=>setSelected([])} onDone={()=>load()} templateName={`${type}-bulk-template.csv`}/>
  {type==="units"&&<section className="panel compactActionPanel"><div><strong>Use MASTER units</strong><span>Copy the common MASTER UQC/unit list into this company, then edit company-specific units if required.</span></div><button className="btn ghost" onClick={async()=>{try{const r=await api("/catalog/units/import-master",{method:"POST"});setMsg(r?.inserted?`${r.inserted} unit(s) copied`:"MASTER units checked");load()}catch(e){setMsg(e.message)}}}>Import MASTER Units</button></section>}
  {show&&<div className="modalOverlay"><section className="panel modalPanel"><div className="formTitle"><div><h3>{edit?"Edit":"Create"} {c.title}</h3></div><button className="iconBtn" onClick={()=>setShow(false)}><X/></button></div><div className="formGrid">{c.fields.filter(f=>!f.noBulkEdit||!edit||f.key!=="code").map(f=><label key={f.key}>{f.label}{f.type==="select"?<select value={form[f.key]??""} onChange={e=>setForm({...form,[f.key]:e.target.value})}>{(f.options||[]).map(o=><option key={o}>{o}</option>)}</select>:<input type={f.type==="number"?"number":"text"} value={form[f.key]??""} onChange={e=>setForm({...form,[f.key]:f.type==="number"?Number(e.target.value):e.target.value})}/>}</label>)}</div><div className="formActions"><button className="btn ghost" onClick={()=>setShow(false)}>Cancel</button><button className="btn primary" onClick={save} disabled={!form.code||!form.name}>Save</button></div></section></div>}
  <section className="panel"><div className="toolbar"><div className="searchBox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load(1)} placeholder={`Search ${c.title.toLowerCase()}...`}/></div><button className="btn ghost" onClick={()=>load(1)}><RefreshCw/>Refresh</button><div className="recordCount">{meta.total||0} records</div></div><DataTable selectable selectedIds={selected} onToggle={toggle} onToggleAll={toggleAll} rows={viewRows} columns={[...cols,{key:"status",label:"Status",render:r=><StatusBadge value={r.status}/>},{key:"actions",label:"Actions",render:r=><div className="rowActions"><button onClick={()=>open(r)}><Pencil/></button><button className="danger" onClick={()=>del(r)}><Trash2/></button></div>} ]}/><div className="paginationBar"><span>Page {meta.page||page} of {Math.max(1,meta.pages||1)}</span><div><button className="btn ghost" disabled={page<=1} onClick={()=>load(page-1)}>Previous</button><button className="btn ghost" disabled={page>=(meta.pages||1)} onClick={()=>load(page+1)}>Next</button></div></div></section>
 </>;
}
