import React,{useEffect,useState} from "react";
import { Plus,RefreshCw,Search,ChevronLeft,ChevronRight,Landmark } from "lucide-react";
import PageHeader from "../components/PageHeader.jsx";
import EditMasterLink from "../components/EditMasterLink.jsx";
import DataTable from "../components/DataTable.jsx";
import BulkTools from "../components/BulkTools.jsx";
import CreateLookupButton from "../components/CreateLookupButton.jsx";
import ScanAndFill from "../components/ScanAndFill.jsx";
import { api } from "../lib/api.js";
import { fetchTransactionParties, partyOptionLabel } from "../lib/partyDirectory.js";

const today=()=>new Date().toISOString().slice(0,10);
const config={
 receipts:{title:"Receipts",description:"Credits received from parties. Bank-statement credits are posted here automatically.",numberField:"receiptNo"},
 payments:{title:"Payments",description:"Debits paid to parties. Bank-statement debits are posted here automatically.",numberField:"paymentNo"},
 expenses:{title:"Expense Management",description:"Expense posting with accounting-safe bulk tools.",numberField:"expenseNo",fields:[{key:"expenseNo",label:"Expense No.",example:"EXP-001",noBulkEdit:true},{key:"accountCode",label:"Expense Account",example:"SYS_INDIRECT_EXPENSE",noBulkEdit:true},{key:"date",label:"Date",type:"date",example:"2026-09-05",noBulkEdit:true},{key:"amount",label:"Amount",type:"number",example:"5000",noBulkEdit:true},{key:"paymentMode",label:"Payment Mode",example:"BANK",noBulkEdit:true},{key:"nature",label:"Nature",type:"select",options:["FIXED","VARIABLE","SEMI_VARIABLE"],example:"FIXED"},{key:"allocationMethod",label:"Allocation Method",type:"select",options:["DIRECT","TURNOVER","QUANTITY","GROSS_PROFIT","EMPLOYEE_COUNT","MANUAL","NONE"],example:"TURNOVER"},{key:"narration",label:"Narration",example:"Office rent",noBulkEdit:true}]}
};

const defaultForm=(type)=>type==="receipts"?{date:today(),customerGlobalId:"",amount:0,mode:"BANK",bankAccountId:"",reference:"",remarks:""}:type==="payments"?{date:today(),partyGlobalId:"",amount:0,mode:"BANK",bankAccountId:"",reference:"",remarks:""}:{accountCode:"SYS_INDIRECT_EXPENSE",amount:0,paymentMode:"BANK",nature:"FIXED",allocationMethod:"TURNOVER",narration:""};
const money=v=>`₹${Number(v||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function FinancialEntryPage({type}){
 const c=config[type],fy=localStorage.getItem("financialYearSelected")||"2026-27";
 const[rows,setRows]=useState([]),[show,setShow]=useState(false),[msg,setMsg]=useState(""),[customers,setCustomers]=useState([]),[accounts,setAccounts]=useState([]),[banks,setBanks]=useState([]),[selected,setSelected]=useState([]),[q,setQ]=useState(""),[page,setPage]=useState(1),[meta,setMeta]=useState({page:1,pages:1,total:0}),[form,setForm]=useState(defaultForm(type));
 const load=async(next=page)=>{try{const d=await api(`/transactions/${type}?financialYear=${encodeURIComponent(fy)}&q=${encodeURIComponent(q)}&page=${next}&limit=50`);setRows(d.items||[]);setMeta(d.meta||{page:next,pages:1,total:(d.items||[]).length});setPage(d.meta?.page||next);}catch(e){setMsg(e.message)}};
 const loadCustomers=()=>fetchTransactionParties(500).then(setCustomers).catch(()=>{});
 const loadBanks=()=>api(`/banks?status=ACTIVE&financialYear=${encodeURIComponent(fy)}&page=1&limit=200`).then(d=>setBanks(d.items||[])).catch(()=>{});
 useEffect(()=>{setSelected([]);setForm(defaultForm(type));load(1);loadCustomers();loadBanks();api("/reference/accounts").then(setAccounts).catch(()=>{})},[type]);
 const applyExpenseScan=(values)=>{if(type!=="expenses")return;setForm(f=>({...f,amount:values.amount||f.amount,paymentMode:values.paymentMode||f.paymentMode,narration:[values.vendorName,values.invoiceNo,values.narration].filter(Boolean).join(" • ")||f.narration}));};
 const requiresBank=type!=="expenses"&&String(form.mode||"").toUpperCase()!=="CASH";
 const save=async()=>{try{if(type==="receipts"&&!form.customerGlobalId)throw new Error("Select a buyer / party");if(type==="payments"&&!form.partyGlobalId)throw new Error("Select a supplier / party");if(requiresBank&&!form.bankAccountId)throw new Error("Select Bank Account");await api(`/transactions/${type}`,{method:"POST",body:JSON.stringify({...form,financialYear:fy,amount:Number(form.amount||0)})});setMsg(`${c.title} entry posted`);setShow(false);setForm(defaultForm(type));load()}catch(e){setMsg(e.message)}};
 const toggle=id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);const toggleAll=(checked,ids)=>setSelected(s=>checked?[...new Set([...s,...ids])]:s.filter(x=>!ids.includes(x)));
 const partyCell=r=>{const pid=type==="receipts"?r.customerGlobalId:r.partyGlobalId;const party=(customers||[]).find(x=>String(x.globalCustomerId||x._id)===String(pid));const name=r.partyNameSnapshot||party?.localName||party?.legalName||pid||"Unmatched Party";return pid?<EditMasterLink to="/dms/customers" id={pid} resource="customer">{name}</EditMasterLink>:<span className="pendingPartyName">{name}</span>};
 const columns=type==="expenses"?[{key:"expenseNo",label:"Voucher"},{key:"date",label:"Date",render:r=>new Date(r.date).toLocaleDateString("en-IN")},{key:"accountCode",label:"Account"},{key:"amount",label:"Amount",render:r=>money(r.amount)},{key:"nature",label:"Nature"},{key:"allocationMethod",label:"Allocation"},{key:"status",label:"Status",status:true}]:[
  {key:c.numberField,label:"Voucher"},{key:"date",label:"Date",render:r=>new Date(r.date).toLocaleDateString("en-IN")},{key:"party",label:"Party",render:partyCell},{key:"amount",label:"Amount",render:r=><strong>{money(r.amount)}</strong>},{key:"mode",label:"Mode"},{key:"bankNameSnapshot",label:"Bank / Cash",render:r=>r.mode==="CASH"?"Cash":(r.bankNameSnapshot||"Bank")},{key:"remarks",label:"Remarks",render:r=>r.remarks||r.reference||"—"},{key:"runningBalance",label:"Run. Bal.",render:r=>r.runningBalance===undefined||r.runningBalance===null?"—":money(r.runningBalance)},{key:"status",label:"Status",status:true}
 ];
 return <>
  <PageHeader title={c.title} description={c.description} onAdd={()=>setShow(true)} addLabel={`Add ${c.title.slice(0,-1)}`}/>
  {msg&&<div className="resultBanner good">{msg}</div>}
  {type==="expenses"?<><BulkTools endpoint={`/transactions/${type}`} fields={c.fields} editFields={c.fields.filter(f=>!f.noBulkEdit)} selectedIds={selected} onClear={()=>setSelected([])} onDone={()=>load()} extraFormData={{financialYear:fy}} extraBody={{financialYear:fy}} schemaForUpload={false} templateName={`${type}-bulk-template.csv`}/><div className="financeSafetyNote">Bulk Delete never erases accounting history; cancellation posts balancing reversals.</div></>:<div className="financeStatementHint"><Landmark size={16}/><span><strong>Bulk upload is done from Bank Accounts.</strong> Upload one simple statement: Date · Party Name · Remarks · Mode · Debit · Credit · Running Balance. Credits appear here as Receipts; Debits appear in Payments.</span></div>}

  {show&&<section className="panel editorPanel financeEntryEditor">{type==="expenses"&&<div className="formTitleActions"><ScanAndFill documentType="EXPENSE" targetPath="/dms/expenses" onApply={applyExpenseScan}/></div>}<div className="formGrid">
   {type!=="expenses"&&<>
    <label>Date *<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label>
    <label>{type==="receipts"?"Party / Buyer":"Party / Supplier"}<div className="lookupSelectRow"><select value={type==="receipts"?form.customerGlobalId:form.partyGlobalId} onChange={e=>setForm({...form,[type==="receipts"?"customerGlobalId":"partyGlobalId"]:e.target.value})}><option value="">Select Party</option>{customers.map(x=><option key={x.globalCustomerId} value={x.globalCustomerId}>{partyOptionLabel(x)}</option>)}</select><CreateLookupButton to="/dms/customers" label="Create" resource="customer" selectedValue={type==="receipts"?form.customerGlobalId:form.partyGlobalId} onReturn={loadCustomers}/></div></label>
    <label>Amount *<input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label>
    <label>Mode<select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value,bankAccountId:e.target.value==="CASH"?"":form.bankAccountId})}>{["BANK","NEFT","RTGS","UPI","CHEQUE","CASH"].map(x=><option key={x}>{x}</option>)}</select></label>
    {requiresBank&&<label>Bank Account *<select value={form.bankAccountId} onChange={e=>setForm({...form,bankAccountId:e.target.value})}><option value="">Select Bank Account</option>{banks.map(b=><option key={b._id} value={b._id}>{b.bankName} • {String(b.accountNumber||"").slice(-4)}{b.isPrimary?" • Primary":""}</option>)}</select></label>}
    <label>Reference / UTR / Cheque<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label className="wideField">Remarks<input value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></label>
   </>}
   {type==="expenses"&&<><label>Expense Account<select value={form.accountCode} onChange={e=>setForm({...form,accountCode:e.target.value})}>{accounts.filter(x=>x.nature==="EXPENSE").map(x=><option key={x.systemCode} value={x.systemCode}>{x.name}</option>)}</select></label><label>Amount<input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Payment Mode<select value={form.paymentMode} onChange={e=>setForm({...form,paymentMode:e.target.value})}><option>BANK</option><option>CASH</option></select></label><label>Nature<select value={form.nature} onChange={e=>setForm({...form,nature:e.target.value})}><option>FIXED</option><option>VARIABLE</option><option>SEMI_VARIABLE</option></select></label><label>Allocation<select value={form.allocationMethod} onChange={e=>setForm({...form,allocationMethod:e.target.value})}>{["DIRECT","TURNOVER","QUANTITY","GROSS_PROFIT","EMPLOYEE_COUNT","MANUAL","NONE"].map(x=><option key={x}>{x}</option>)}</select></label><label>Narration<input value={form.narration} onChange={e=>setForm({...form,narration:e.target.value})}/></label></>}
  </div><div className="formActions"><button className="btn ghost" onClick={()=>setShow(false)}>Cancel</button><button className="btn primary" disabled={Number(form.amount||0)<=0||(type==="receipts"&&!form.customerGlobalId)||(type==="payments"&&!form.partyGlobalId)||(requiresBank&&!form.bankAccountId)} onClick={save}><Plus/>Post Entry</button></div></section>}

  <section className="panel"><div className="toolbar"><div className="searchBox"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(setSelected([]),load(1))} placeholder={`Search ${c.title.toLowerCase()}...`}/></div><button className="btn ghost" onClick={()=>load()}><RefreshCw/>Refresh</button><div className="recordCount">{meta.total||0} records • FY {fy}</div></div><DataTable selectable={type==="expenses"} selectedIds={selected} onToggle={toggle} onToggleAll={toggleAll} rows={rows} columns={columns}/><div className="paginationBar"><span>Page {meta.page||page} of {Math.max(1,meta.pages||1)} • {meta.total||0} records</span><div><button className="btn ghost" disabled={(meta.page||page)<=1} onClick={()=>{setSelected([]);load((meta.page||page)-1)}}><ChevronLeft size={15}/>Previous</button><button className="btn ghost" disabled={(meta.page||page)>=(meta.pages||1)} onClick={()=>{setSelected([]);load((meta.page||page)+1)}}>Next<ChevronRight size={15}/></button></div></div></section>
 </>;
}
