import React,{useEffect,useRef,useState} from "react";
import {Download,MapPin,Pencil,Plus,RefreshCw,Search,Trash2,Truck,Upload} from "lucide-react";
import PageHeader from "../components/PageHeader.jsx";
import DataTable from "../components/DataTable.jsx";
import StatusBadge from "../components/StatusBadge.jsx";
import EditMasterLink from "../components/EditMasterLink.jsx";
import {api} from "../lib/api.js";

const blank={name:"",address:"",pincode:"",contactPerson:"",mobile:"",landline:"",email:"",directoryGroups:"",categories:"",listingOccurrences:1,sourceUrls:"",status:"ACTIVE"};
const blankStation={name:"",stationType:"BOTH",address:"",pincode:"",area:"",city:"",district:"",state:"",servicePincodes:"",serviceCities:"",serviceStates:"",status:"ACTIVE"};
const join=v=>Array.isArray(v)?v.join("; "):String(v||"");
const list=v=>String(v||"").split(/[,;|\n]+/).map(x=>x.trim()).filter(Boolean);
export default function GlobalTransporterPage(){
 const fileRef=useRef(null);
 const[rows,setRows]=useState([]),[meta,setMeta]=useState({page:1,pages:1,total:0,limit:100}),[q,setQ]=useState(""),[msg,setMsg]=useState(""),[editor,setEditor]=useState(null),[form,setForm]=useState(blank),[uploading,setUploading]=useState(false),[summary,setSummary]=useState(null);
 const[stations,setStations]=useState([]),[stationEdit,setStationEdit]=useState(null),[stationForm,setStationForm]=useState(blankStation);
 const load=async(next=meta.page||1)=>{try{const d=await api(`/master/transporters?q=${encodeURIComponent(q)}&page=${next}&limit=${meta.limit||100}`);setRows(d.items||[]);setMeta(d.meta||{page:next,pages:1,total:0,limit:100})}catch(e){setMsg(e.message)}};
 const loadStations=async gid=>{if(!gid){setStations([]);return []}try{const d=await api(`/master/transporter-stations?globalTransporterId=${encodeURIComponent(gid)}&status=ACTIVE`);setStations(d.items||[]);return d.items||[]}catch(e){setMsg(e.message);setStations([]);return []}};
 useEffect(()=>{load(1)},[]);
 const openNew=()=>{setEditor("new");setForm(blank);setStations([]);setStationEdit(null);setStationForm(blankStation);setMsg("")};
 const openEdit=async r=>{setEditor(r);setForm({...blank,...r,directoryGroups:join(r.directoryGroups),categories:join(r.categories),sourceUrls:join(r.sourceUrls)});setStationEdit(null);setStationForm(blankStation);await loadStations(r.globalTransporterId)};
 const payload=()=>({...form,directoryGroups:list(form.directoryGroups),categories:list(form.categories),sourceUrls:list(form.sourceUrls)});
 const save=async()=>{try{const saved=await api(editor==="new"?"/master/transporters":`/master/transporters/${editor._id}`,{method:editor==="new"?"POST":"PUT",body:JSON.stringify(payload())});setMsg(editor==="new"?"Global transporter created. Add its booking/delivery stations below.":"Global transporter updated");setEditor(saved);setForm({...blank,...saved,directoryGroups:join(saved.directoryGroups),categories:join(saved.categories),sourceUrls:join(saved.sourceUrls)});await loadStations(saved.globalTransporterId);await load(1)}catch(e){setMsg(e.message)}};
 const remove=async r=>{if(!confirm(`Deactivate ${r.name}?`))return;try{await api(`/master/transporters/${r._id}`,{method:"DELETE"});setMsg("Global transporter deactivated");load()}catch(e){setMsg(e.message)}};
 const upload=async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;setUploading(true);setSummary(null);try{const fd=new FormData();fd.append("file",file);const d=await api("/master/transporters/bulk-upload",{method:"POST",body:fd});setSummary(d);setMsg(`Transporter import: ${Number(d.valid||0).toLocaleString("en-IN")} valid • ${Number(d.inserted||0).toLocaleString("en-IN")} new • ${Number(d.updated||0).toLocaleString("en-IN")} updated`);await load(1)}catch(err){setMsg(err.message)}finally{setUploading(false)}};
 const template=()=>{const csv="Firm Name,Address,Pincode,Contact Person,Mobile Number,Landline Number,Email,Directory Groups,Categories,Listing Occurrences,Source URLs\nABC Transport,Beltola Guwahati,781028,Rakesh,9876543210,0361-1234567,abc@example.com,North East,Guwahati,1,https://example.com\n";const b=new Blob([csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="Global_Transporter_Master_Template.csv";a.click();URL.revokeObjectURL(a.href)};
 const openStation=st=>{setStationEdit(st||"new");setStationForm(st?{...blankStation,...st,servicePincodes:join(st.servicePincodes),serviceCities:join(st.serviceCities),serviceStates:join(st.serviceStates)}:blankStation)};
 const saveStation=async()=>{try{if(!editor?.globalTransporterId)throw new Error("Save transporter first");if(!stationForm.name.trim())throw new Error("Station name is required");const body={...stationForm,globalTransporterId:editor.globalTransporterId,pincode:String(stationForm.pincode||"").replace(/\D/g,"").slice(0,6),servicePincodes:list(stationForm.servicePincodes),serviceCities:list(stationForm.serviceCities),serviceStates:list(stationForm.serviceStates)};await api(stationEdit==="new"?"/master/transporter-stations":`/master/transporter-stations/${stationEdit._id}`,{method:stationEdit==="new"?"POST":"PUT",body:JSON.stringify(body)});setStationEdit(null);setStationForm(blankStation);await loadStations(editor.globalTransporterId);setMsg("Transporter station saved")}catch(e){setMsg(e.message)}};
 const removeStation=async st=>{if(!confirm(`Deactivate station ${st.name}?`))return;try{await api(`/master/transporter-stations/${st._id}`,{method:"DELETE"});await loadStations(editor.globalTransporterId)}catch(e){setMsg(e.message)}};
 return <>
  <PageHeader title="Global Transporter Master" description="All-India transporter directory with separate booking/delivery stations and service areas." onAdd={openNew} onUpload={()=>fileRef.current?.click()} addLabel="Add Transporter"/>
  <input ref={fileRef} hidden type="file" accept=".xlsx,.xls,.csv" onChange={upload}/>
  {msg&&<div className="resultBanner good">{msg}</div>}
  <section className="panel"><div className="toolbar"><div className="searchBox"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load(1)} placeholder="Search transporter, station, area, mobile, email..."/></div><button className="btn ghost" onClick={()=>fileRef.current?.click()} disabled={uploading}><Upload size={15}/>{uploading?"Importing...":"Bulk Upload"}</button><button className="btn ghost" onClick={template}><Download size={15}/>Template</button><button className="btn ghost" onClick={()=>load()}><RefreshCw size={15}/>Refresh</button><span className="recordCount"><Truck size={15}/>{Number(meta.total||0).toLocaleString("en-IN")} transporters</span></div></section>
  {summary&&<section className="panel uploadSummary"><Truck/><div><strong>Last Global Transporter import</strong><span>{Number(summary.received||0).toLocaleString("en-IN")} rows • {Number(summary.valid||0).toLocaleString("en-IN")} valid • {Number(summary.inserted||0).toLocaleString("en-IN")} inserted • {Number(summary.updated||0).toLocaleString("en-IN")} updated • {Number(summary.invalid||0).toLocaleString("en-IN")} invalid</span></div></section>}
  {editor&&<section className="panel editorPanel"><div className="formTitle"><div><h3>{editor==="new"?"Add Global Transporter":"Edit Global Transporter"}</h3><span>Company identity and station network are stored separately. One transporter can have any number of booking/delivery stations.</span></div><button className="btn ghost" onClick={()=>setEditor(null)}>Close</button></div><div className="formGrid dynamicForm"><label>Transporter / Firm Name *<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Contact Person<input value={form.contactPerson} onChange={e=>setForm({...form,contactPerson:e.target.value})}/></label><label>Mobile<input value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/></label><label>Landline<input value={form.landline} onChange={e=>setForm({...form,landline:e.target.value})}/></label><label>Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Pincode<input value={form.pincode} onChange={e=>setForm({...form,pincode:e.target.value})}/></label><label>Directory Group<input value={form.directoryGroups} onChange={e=>setForm({...form,directoryGroups:e.target.value})} placeholder="Delhi NCR; North East"/></label><label>Legacy Station Tags<input value={form.categories} onChange={e=>setForm({...form,categories:e.target.value})} placeholder="Imported station/category tags"/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></label><label className="fullField">Address<textarea rows="3" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="fullField">Source URLs<textarea rows="2" value={form.sourceUrls} onChange={e=>setForm({...form,sourceUrls:e.target.value})}/></label></div><div className="formActions"><button className="btn ghost" onClick={()=>setEditor(null)}>Cancel</button><button className="btn primary" onClick={save} disabled={!form.name}>Save</button></div>
   {editor!=="new"&&<><div className="sectionLabel" style={{marginTop:16}}><MapPin size={14}/> Stations / Service Network <button className="iconBtn" title="Add station" onClick={()=>openStation(null)}><Plus size={14}/></button></div>{stationEdit&&<div className="subCard"><div className="formGrid"><label>Station Name *<input value={stationForm.name} onChange={e=>setStationForm({...stationForm,name:e.target.value})}/></label><label>Type<select value={stationForm.stationType} onChange={e=>setStationForm({...stationForm,stationType:e.target.value})}><option>BOOKING</option><option>DELIVERY</option><option>BOTH</option></select></label><label>Pincode<input value={stationForm.pincode} onChange={e=>setStationForm({...stationForm,pincode:e.target.value})}/></label><label>Area<input value={stationForm.area} onChange={e=>setStationForm({...stationForm,area:e.target.value})}/></label><label>City<input value={stationForm.city} onChange={e=>setStationForm({...stationForm,city:e.target.value})}/></label><label>District<input value={stationForm.district} onChange={e=>setStationForm({...stationForm,district:e.target.value})}/></label><label>State<input value={stationForm.state} onChange={e=>setStationForm({...stationForm,state:e.target.value})}/></label><label>Service Pincodes<input value={stationForm.servicePincodes} onChange={e=>setStationForm({...stationForm,servicePincodes:e.target.value})} placeholder="110001, 110002"/></label><label>Service Cities<input value={stationForm.serviceCities} onChange={e=>setStationForm({...stationForm,serviceCities:e.target.value})} placeholder="Delhi, Noida"/></label><label>Service States<input value={stationForm.serviceStates} onChange={e=>setStationForm({...stationForm,serviceStates:e.target.value})}/></label><label className="span2">Address<input value={stationForm.address} onChange={e=>setStationForm({...stationForm,address:e.target.value})}/></label></div><div className="formActions"><button className="btn ghost" onClick={()=>setStationEdit(null)}>Cancel</button><button className="btn primary" onClick={saveStation}>Save Station</button></div></div>}<div className="transporterStationStack">{stations.map(st=><div className="subCard stationSummaryCard" key={st._id}><div><strong>{st.name}</strong><small>{st.stationType} • {[st.city,st.state,st.pincode].filter(Boolean).join(" • ")}</small><span>{(st.servicePincodes||[]).length} service pincodes • {(st.serviceCities||[]).length} service cities</span></div><div className="rowActions"><button onClick={()=>openStation(st)}><Pencil size={14}/></button><button className="danger" onClick={()=>removeStation(st)}><Trash2 size={14}/></button></div></div>)}</div></>}
  </section>}
  <section className="panel"><DataTable rows={rows} columns={[{key:"globalTransporterId",label:"Global ID"},{key:"name",label:"Transporter",render:r=><EditMasterLink onClick={()=>openEdit(r)}>{r.name}</EditMasterLink>},{key:"categories",label:"Imported Station Tags",render:r=>(r.categories||[]).join(", ")||"—"},{key:"directoryGroups",label:"Region",render:r=>(r.directoryGroups||[]).join(", ")||"—"},{key:"contactPerson",label:"Contact Person"},{key:"mobile",label:"Mobile"},{key:"email",label:"Email"},{key:"address",label:"Address"},{key:"status",label:"Status",render:r=><StatusBadge value={r.status}/>},{key:"actions",label:"Actions",render:r=><div className="rowActions"><button title="Edit" onClick={()=>openEdit(r)}><Pencil/></button><button className="danger" title="Deactivate" onClick={()=>remove(r)}><Trash2/></button></div>}]} /><div className="paginationBar"><span>Page {meta.page||1} of {Math.max(1,meta.pages||1)} • {Number(meta.total||0).toLocaleString("en-IN")} records</span><div><button className="btn ghost" disabled={(meta.page||1)<=1} onClick={()=>load((meta.page||1)-1)}>Previous</button><button className="btn ghost" disabled={(meta.page||1)>=(meta.pages||1)} onClick={()=>load((meta.page||1)+1)}>Next</button></div></div></section>
 </>;
}
