import React,{useEffect,useRef,useState} from "react";
import {Download,Landmark,Pencil,RefreshCw,Search,Trash2,Upload} from "lucide-react";
import PageHeader from "../components/PageHeader.jsx";
import DataTable from "../components/DataTable.jsx";
import StatusBadge from "../components/StatusBadge.jsx";
import EditMasterLink from "../components/EditMasterLink.jsx";
import {api} from "../lib/api.js";

const blank={ifsc:"",bank:"",branch:"",address:"",city:"",state:"",stdCode:"",phone:"",status:"ACTIVE"};
const contact=row=>row?.phone?(row?.stdCode?`${String(row.stdCode).startsWith("0")?row.stdCode:`0${row.stdCode}`}-${row.phone}`:row.phone):"—";

export default function IfscPage(){
 const fileRef=useRef(null);
 const[rows,setRows]=useState([]),[meta,setMeta]=useState({page:1,pages:1,total:0,limit:100}),[q,setQ]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[editor,setEditor]=useState(null),[form,setForm]=useState(blank),[uploading,setUploading]=useState(false),[summary,setSummary]=useState(null);
 const load=async(next=meta.page||1)=>{setLoading(true);try{const d=await api(`/master/ifsc?q=${encodeURIComponent(q)}&page=${next}&limit=${meta.limit||100}`);setRows(d.items||[]);setMeta(d.meta||{page:next,pages:1,total:0,limit:100})}catch(e){setMessage(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load(1)},[]);
 const openNew=()=>{setEditor("new");setForm(blank);setMessage("")};
 const openEdit=r=>{setEditor(r);setForm({ifsc:r.ifsc||"",bank:r.bank||"",branch:r.branch||"",address:r.address||"",city:r.city||"",state:r.state||"",stdCode:r.stdCode||"",phone:r.phone||"",status:r.status||"ACTIVE"})};
 const save=async()=>{try{const url=editor==="new"?"/master/ifsc":`/master/ifsc/${editor._id}`;await api(url,{method:editor==="new"?"POST":"PUT",body:JSON.stringify(form)});setMessage(editor==="new"?"IFSC branch created":"IFSC branch updated");setEditor(null);await load(1)}catch(e){setMessage(e.message)}};
 const remove=async r=>{if(!confirm(`Deactivate IFSC ${r.ifsc}?`))return;try{await api(`/master/ifsc/${r._id}`,{method:"DELETE"});setMessage("IFSC branch deactivated");load()}catch(e){setMessage(e.message)}};
 const upload=async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;setUploading(true);setSummary(null);try{const fd=new FormData();fd.append("file",file);const d=await api("/master/ifsc/bulk-upload",{method:"POST",body:fd});setSummary(d);setMessage(`IFSC import complete: ${Number(d.valid||0).toLocaleString("en-IN")} valid • ${Number(d.inserted||0).toLocaleString("en-IN")} new • ${Number(d.updated||0).toLocaleString("en-IN")} updated`);await load(1)}catch(err){setMessage(err.message)}finally{setUploading(false)}};
 const template=()=>{const csv="IFSC,BANK,BRANCH,ADDRESS,CITY,STATE,STD CODE,PHONE\nSBIN0000001,STATE BANK OF INDIA,MAIN BRANCH,Example Address,GUWAHATI,ASSAM,361,1234567\n";const b=new Blob([csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="IFSC_Master_Upload_Template.csv";a.click();URL.revokeObjectURL(a.href)};
 return <>
  <PageHeader title="IFSC / Bank Branch Master" description="Global bank-branch database used for automatic bank detail fill everywhere in DMS." onAdd={openNew} onUpload={()=>fileRef.current?.click()} addLabel="Add IFSC"/>
  <input ref={fileRef} hidden type="file" accept=".xlsx,.xls,.csv" onChange={upload}/>
  {message&&<div className="resultBanner good">{message}</div>}
  <section className="panel"><div className="toolbar"><div className="searchBox"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load(1)} placeholder="Search IFSC, bank, branch, city, state..."/></div><button className="btn ghost" onClick={()=>fileRef.current?.click()} disabled={uploading}><Upload size={15}/>{uploading?"Importing...":"Bulk Upload"}</button><button className="btn ghost" onClick={template}><Download size={15}/>Template</button><button className="btn ghost" onClick={()=>load()}><RefreshCw size={15}/>Refresh</button><span className="recordCount"><Landmark size={15}/>{Number(meta.total||0).toLocaleString("en-IN")} branches</span></div></section>
  {summary&&<section className="panel uploadSummary"><Landmark/><div><strong>Last IFSC import</strong><span>{Number(summary.received||0).toLocaleString("en-IN")} rows • {Number(summary.valid||0).toLocaleString("en-IN")} valid • {Number(summary.inserted||0).toLocaleString("en-IN")} inserted • {Number(summary.updated||0).toLocaleString("en-IN")} updated • {Number(summary.invalid||0).toLocaleString("en-IN")} invalid</span></div></section>}
  {editor&&<section className="panel editorPanel"><div className="formTitle"><div><h3>{editor==="new"?"Add IFSC Branch":"Edit IFSC Branch"}</h3><span>IFSC is the key. Bank details are auto-filled from this master throughout the application.</span></div><button className="btn ghost" onClick={()=>setEditor(null)}>Close</button></div><div className="formGrid dynamicForm"><label>IFSC *<input value={form.ifsc} maxLength={11} onChange={e=>setForm({...form,ifsc:e.target.value.toUpperCase().replace(/\s/g,"")})}/></label><label>Bank *<input value={form.bank} onChange={e=>setForm({...form,bank:e.target.value})}/></label><label>Branch / Area<input value={form.branch} onChange={e=>setForm({...form,branch:e.target.value})}/></label><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>State<input value={form.state} onChange={e=>setForm({...form,state:e.target.value})}/></label><label>STD Code<input value={form.stdCode} onChange={e=>setForm({...form,stdCode:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></label><label className="fullField">Bank Address<textarea rows="3" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></div><div className="formActions"><button className="btn ghost" onClick={()=>setEditor(null)}>Cancel</button><button className="btn primary" onClick={save} disabled={!form.ifsc||!form.bank}>Save</button></div></section>}
  <section className="panel"><DataTable rows={rows} columns={[{key:"ifsc",label:"IFSC",render:r=><EditMasterLink onClick={()=>openEdit(r)}>{r.ifsc}</EditMasterLink>},{key:"bank",label:"Bank"},{key:"branch",label:"Branch / Area"},{key:"city",label:"City"},{key:"state",label:"State"},{key:"address",label:"Address"},{key:"phone",label:"Contact",render:contact},{key:"status",label:"Status",render:r=><StatusBadge value={r.status}/>},{key:"actions",label:"Actions",render:r=><div className="rowActions"><button title="Edit" onClick={()=>openEdit(r)}><Pencil/></button><button className="danger" title="Deactivate" onClick={()=>remove(r)}><Trash2/></button></div>}]} /><div className="paginationBar"><span>Page {meta.page||1} of {Math.max(1,meta.pages||1)} • {Number(meta.total||0).toLocaleString("en-IN")} records</span><div><button className="btn ghost" disabled={(meta.page||1)<=1} onClick={()=>load((meta.page||1)-1)}>Previous</button><button className="btn ghost" disabled={(meta.page||1)>=(meta.pages||1)} onClick={()=>load((meta.page||1)+1)}>Next</button></div></div></section>
 </>;
}
