import React from "react";
import CrudPage from "./CrudPage.jsx";
import CustomerPage from "./CustomerPage.jsx";
import UnassignedCustomerPage from "./UnassignedCustomerPage.jsx";
import UserCustomerMasterPage from "./UserCustomerMasterPage.jsx";
import ProductPage from "./ProductPage.jsx";
import LeadPage from "./LeadPage.jsx";
import TargetPage from "./TargetPage.jsx";
import PricingPage from "./PricingPage.jsx";
import ReportsPage from "./ReportsPage.jsx";
import ReportCenterPage from "./ReportCenterPage.jsx";
import DashboardPage from "./DashboardPage.jsx";
import PlanPage from "./PlanPage.jsx";
import SalesInvoicePage from "./SalesInvoicePage.jsx";
import SalesListPage from "./SalesListPage.jsx";
import SalesWithProductPage from "./SalesWithProductPage.jsx";
import RolePermissionPage from "./RolePermissionPage.jsx";
import GroupManagementPage from "./GroupManagementPage.jsx";
import DesignationSecurityPage from "./DesignationSecurityPage.jsx";
import HierarchyPage from "./HierarchyPage.jsx";
import DepartmentManagementPage from "./DepartmentManagementPage.jsx";
import DepartmentRoleAssignmentPage from "./DepartmentRoleAssignmentPage.jsx";
import EmployeesPage from "./EmployeesPage.jsx";
import RecruitmentPage from "./RecruitmentPage.jsx";
import SuperadminPage from "./SuperadminPage.jsx";
import BrandingPage from "./BrandingPage.jsx";
import * as GstApiModule from "./GstApiPage.jsx";
const GstApiPage = GstApiModule.default || GstApiModule.GstApiPage || null;
import LiveReportPage from "./LiveReportPage.jsx";
import LedgerPage from "./LedgerPage.jsx";
import FinancialEntryPage from "./FinancialEntryPage.jsx";
import TransporterPage from "./TransporterPage.jsx";
import PincodePage from "./PincodePage.jsx";
import IfscPage from "./IfscPage.jsx";
import GlobalTransporterPage from "./GlobalTransporterPage.jsx";
import SalesPincodeAllotmentPage from "./SalesPincodeAllotmentPage.jsx";
import CompanySettingsPage from "./CompanySettingsPage.jsx";
import DmsCatalogPage from "./DmsCatalogPage.jsx";
import PriceListPage from "./PriceListPage.jsx";
import PurchaseInvoicePage from "./PurchaseInvoicePage.jsx";
import DocumentNotePage from "./DocumentNotePage.jsx";
import PurchaseAutomationPage from "./PurchaseAutomationPage.jsx";
import BankAccountPage from "./BankAccountPage.jsx";
import BankTransactionPage from "./BankTransactionPage.jsx";
import BranchManagementPage from "./BranchManagementPage.jsx";
import FormLibraryPage from "./FormLibraryPage.jsx";
import LegacyMigrationPage from "./LegacyMigrationPage.jsx";
import GstReportsPage from "./GstReportsPage.jsx";
import OrderControlCenter from "./OrderControlCenter.jsx";
import DispatchWorkspace from "./DispatchWorkspace.jsx";
import FamilyFinancePage from "./FamilyFinancePage.jsx";
import { reportLikePaths } from "../config/resourceSchemas.js";
export default function ModulePage({page}){
 if(page.kind==="dashboard")return <DashboardPage appKey={page.app}/>;
 if(page.kind==="customers")return <UserCustomerMasterPage initialMode="customer"/>;
 if(page.kind==="customer-approvals")return <CustomerPage approvalsOnly/>;
 if(page.kind==="unassigned-customers")return <UnassignedCustomerPage/>;
 if(page.kind==="company-settings")return <CompanySettingsPage/>;
 if(page.kind==="products")return <ProductPage/>;
 if(page.kind==="leads")return <LeadPage/>;
 if(page.kind==="target")return <TargetPage/>;
 if(page.kind==="pricing")return <PricingPage/>;
 if(page.kind==="report-center")return <ReportCenterPage/>;
 if(page.kind==="reports")return <ReportsPage/>;
 if(page.kind==="plans")return <PlanPage/>;
 if(page.kind==="sales-invoices")return <SalesInvoicePage/>;
 if(page.kind==="sales-list")return <SalesListPage/>;
 if(page.kind==="sales-with-product")return <SalesWithProductPage/>;
 if(page.kind==="credit-notes")return <DocumentNotePage documentType="CREDIT_NOTE"/>;
 if(page.kind==="delivery-notes")return <DocumentNotePage documentType="DELIVERY_NOTE"/>;
 if(page.kind==="order-control")return <OrderControlCenter initialTab="ORDERS"/>;
 if(page.kind==="dispatch-control")return <DispatchWorkspace/>;
 if(page.kind==="order-returns")return <OrderControlCenter initialTab="RETURNS"/>;
 if(page.path==="/dms/purchase-request")return <PurchaseAutomationPage initialTab="ORDER_SHEET"/>;
 if(page.path==="/dms/rfq")return <PurchaseAutomationPage initialTab="RFQ"/>;
 if(page.path==="/dms/purchase-orders")return <PurchaseAutomationPage initialTab="PO"/>;
 if(page.path==="/dms/grn")return <PurchaseAutomationPage initialTab="GRN"/>;
 if(page.path==="/dms/purchase-returns")return <PurchaseAutomationPage initialTab="COMPLAINTS"/>;
 if(page.kind==="purchase-invoices")return <PurchaseInvoicePage/>;
 if(page.kind==="debit-notes")return <DocumentNotePage documentType="DEBIT_NOTE"/>;
 if(page.kind==="bank-accounts")return <BankAccountPage/>;
 if(page.kind==="bank-transactions")return <BankTransactionPage/>;
 if(page.kind==="scan-forms")return <FormLibraryPage/>;
 if(page.kind==="legacy-migration")return <LegacyMigrationPage/>;
 if(page.kind==="gst-reports"){const initial=page.path==="/dms/gstr2b"?"GSTR2B":page.path==="/dms/gstr3b"?"GSTR3B":page.path==="/dms/hsn-wise-report"?"HSN":page.path==="/dms/gst-input-output"?"INPUTOUTPUT":page.path==="/dms/tax-report"?"TAX":"GSTR1";return <GstReportsPage initialReport={initial}/>;}
 if(page.kind==="dms-units")return <DmsCatalogPage type="units"/>;
 if(page.kind==="customer-grades")return <DmsCatalogPage type="grades"/>;
 if(page.kind==="product-categories")return <DmsCatalogPage type="categories"/>;
 if(page.kind==="price-list")return <PriceListPage/>;
 if(page.kind==="users")return <UserCustomerMasterPage initialMode="user"/>;
 if(page.kind==="branches")return <BranchManagementPage/>;
 if(page.kind==="permissions")return <RolePermissionPage master/>;
 if(page.kind==="designation-security")return <DesignationSecurityPage/>;
 if(page.kind==="roles")return <RolePermissionPage/>;
 if(page.kind==="master-departments")return <DepartmentManagementPage/>;
 if(page.kind==="department-role-assignment")return <DepartmentRoleAssignmentPage/>;
 if(page.kind==="family-ai")return <FamilyFinancePage/>;
 if(page.kind==="groups")return <GroupManagementPage/>;
 if(page.kind==="hierarchy")return <HierarchyPage/>;
 if(page.kind==="employees")return <EmployeesPage/>;
 if(page.kind==="recruitment")return <RecruitmentPage/>;
 if(page.kind==="superadmins")return <SuperadminPage/>;
 if(page.kind==="branding")return <BrandingPage/>;
 if(page.kind==="gst-api")return GstApiPage ? <GstApiPage/> : <div className="panel"><strong>GST API page could not load.</strong></div>;
 if(page.kind==="pincodes")return <PincodePage/>;
 if(page.kind==="ifsc-master")return <IfscPage/>;
 if(page.kind==="transporter-master")return <GlobalTransporterPage/>;
 if(page.kind==="sales-pincode-allotment")return <SalesPincodeAllotmentPage/>;
 if(page.path==="/dms/transporters")return <TransporterPage/>;
 if(page.path==="/dms/receipts"||page.path==="/dms/payments"||page.path==="/dms/banking")return <BankTransactionPage/>;
 if(page.path==="/dms/expenses")return <FinancialEntryPage type="expenses"/>;
 if(page.path==="/dms/ledger")return <LedgerPage page={page}/>;
 if(reportLikePaths.has(page.path))return <LiveReportPage page={page}/>;
 return <CrudPage page={page}/>;
}
