import React,{useEffect,useState} from "react";
import {Calculator,Save,ShieldAlert,Trash2} from "lucide-react";
import PageHeader from "../components/PageHeader.jsx";
import DataTable from "../components/DataTable.jsx";
import {api} from "../lib/api.js";
import {isAdminUser} from "../lib/adminVisibility.js";

export default function PricingPage(){
 const admin=isAdminUser();
 const[landed,setLanded]=useState(100),[sale,setSale]=useState(108),[minimum,setMinimum]=useState(3),[redMax,setRedMax]=useState(5),[blueMax,setBlueMax]=useState(10),[name,setName]=useState("Company Default"),[rows,setRows]=useState([]),[msg,setMsg]=useState("");
 const load=()=>api("/modules/dms/price-management").then(d=>setRows(d.items||[])).catch(e=>setMsg(e.message));
 useEffect(()=>{if(admin)load()},[admin]);
 if(!admin)return <><PageHeader title="Price Management" description="Administrator-only pricing and margin controls." actions={false}/><div className="adminSensitiveNotice">Profit, margin and price-health controls are visible only to Admin users.</div></>;
 const pct=landed?((sale-landed)/landed*100):0,blocked=pct<minimum,color=blocked?"blocked":pct<redMax?"red":pct<blueMax?"blue":"green";
 const save=async()=>{try{await api("/modules/dms/price-management",{method:"POST",body:JSON.stringify({title:name,reference:`PRICE-${Date.now()}`,status:"ACTIVE",data:{minimumProfitPct:Number(minimum),redMax:Number(redMax),blueMax:Number(blueMax)}})});setMsg("Pricing rule saved");load()}catch(e){setMsg(e.message)}};
 const del=async r=>{if(!confirm(`Delete ${r.title}?`))return;try{await api(`/modules/dms/price-management/${r._id}`,{method:"DELETE"});load()}catch(e){setMsg(e.message)}};
 return <><PageHeader title="Price Management" description="Dynamic company/category/product minimum margin rules with real-time red/blue/green profit health and backend enforcement." actions={false}/>{msg&&<div className="resultBanner good">{msg}</div>}<div className="pricingDemo panel"><div className="pricingInputs"><label>Rule Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Landed Price<input type="number" value={landed} onChange={e=>setLanded(Number(e.target.value))}/></label><label>Minimum Profit %<input type="number" value={minimum} onChange={e=>setMinimum(Number(e.target.value))}/></label><label>Red Range Upper %<input type="number" value={redMax} onChange={e=>setRedMax(Number(e.target.value))}/></label><label>Blue Range Upper %<input type="number" value={blueMax} onChange={e=>setBlueMax(Number(e.target.value))}/></label><label>Test Sale Price<input type="number" value={sale} onChange={e=>setSale(Number(e.target.value))}/></label></div><div className={`priceHealth ${color}`}><Calculator/><span>Effective Profit</span><strong>{pct.toFixed(2)}%</strong><small>Minimum sale ₹{(landed*(1+minimum/100)).toFixed(2)}</small></div>{blocked&&<div className="priceBlock"><ShieldAlert/> Sale blocked — effective selling price is below the minimum profit rule.</div>}<div className="bandLegend"><span className="red">{minimum}–{redMax}% Low</span><span className="blue">{redMax}–{blueMax}% Normal</span><span className="green">{blueMax}%+ Good</span><em>Product-specific minimum can override this company rule.</em></div><div className="formActions"><button className="btn primary" onClick={save}><Save/>Save Pricing Rule</button></div></div><section className="panel" style={{marginTop:14}}><DataTable rows={rows.map(r=>({...r,...(r.data||{})}))} columns={[{key:"title",label:"Rule"},{key:"minimumProfitPct",label:"Minimum %"},{key:"redMax",label:"Red Max"},{key:"blueMax",label:"Blue Max"},{key:"status",label:"Status",status:true},{key:"actions",label:"Actions",render:r=><div className="rowActions"><button className="danger" onClick={()=>del(r)}><Trash2/></button></div>}]} /></section></>
}
