import React,{useEffect,useState} from "react";
import { Printer,FileSpreadsheet,Search,Monitor } from "lucide-react";
import PageHeader from "../components/PageHeader.jsx";
import DataTable from "../components/DataTable.jsx";
import { api } from "../lib/api.js";
import { accessForPath } from "../lib/permissionAccess.js";

const esc=v=>String(v??"").replaceAll('"','""');

export default function ReportsPage(){
  const[reports,setReports]=useState([]);
  const[q,setQ]=useState("");
  const[selected,setSelected]=useState(null);
  const[data,setData]=useState(null);
  const[msg,setMsg]=useState("");
  const access=accessForPath("/dms/reports");

  useEffect(()=>{api("/reports/catalog").then(setReports).catch(e=>setMsg(e.message))},[]);
  const list=reports.filter(r=>r.name.toLowerCase().includes(q.toLowerCase()));

  const run=async(r)=>{
    try{
      const d=await api(`/reports/run?name=${encodeURIComponent(r.name)}&financialYear=${encodeURIComponent(localStorage.getItem("financialYearSelected")||"2026-27")}`);
      setSelected(r);setData(d);return d;
    }catch(e){setMsg(e.message);return null}
  };

  const csv=async r=>{
    const d=await run(r);if(!d)return;
    const rows=d.rows||[],keys=[...new Set(rows.flatMap(x=>Object.keys(x)))];
    const content=[keys.join(","),...rows.map(x=>keys.map(k=>`"${esc(x[k] instanceof Object?JSON.stringify(x[k]):x[k])}"`).join(","))].join("\n");
    const blob=new Blob([content],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");
    a.href=URL.createObjectURL(blob);a.download=`${r.name.replace(/[^a-z0-9]+/gi,"_")}.csv`;a.click();URL.revokeObjectURL(a.href);
  };
  const print=async r=>{await run(r);setTimeout(()=>window.print(),100)};
  const cols=data?.rows?.length?Object.keys(data.rows[0]).slice(0,8).map(k=>({key:k,label:k.replace(/([A-Z])/g," $1")})):[];

  return <>
    <PageHeader title="All Reports" description="Permission-aware reports for DMS, Accounts, GST, Targets, HR, Production, MASTER and audit." actions={false}/>
    {msg&&<div className="resultBanner bad">{msg}</div>}
    <div className="reportSearch"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search reports..."/></div>
    <div className="reportGrid">
      {list.map(r=><article key={r.id}>
        <div><span>{r.id}</span><h3>{r.name}</h3></div>
        <div className="reportActions">
          {access.view&&<button onClick={()=>run(r)}><Monitor/>Screen</button>}
          {access.download&&<button onClick={()=>csv(r)}><FileSpreadsheet/>Excel</button>}
          {access.print&&<button onClick={()=>print(r)}><Printer/>PDF/Print</button>}
        </div>
        <footer>This page is generated by the Rupioo Global System.</footer>
      </article>)}
    </div>
    {selected&&data&&<section className="panel" style={{marginTop:16}}>
      <div className="panelHead"><div><h3>{selected.name}</h3><p>Generated {new Date(data.generatedAt).toLocaleString("en-IN")}</p></div></div>
      <div className="summaryCards">{Object.entries(data.summary||{}).map(([k,v])=><div key={k}><strong>{typeof v==="number"?v.toLocaleString("en-IN"):String(v)}</strong><span>{k}</span></div>)}</div>
      <DataTable rows={data.rows||[]} columns={cols}/>
    </section>}
  </>;
}
