import React, { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { BrainCircuit, CheckCircle2, FileText, PackageCheck, RefreshCw, Send, Truck, Upload, AlertTriangle, IndianRupee } from "lucide-react";
import "../purchase-ai.css";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5050/api";
const money = (v) => `₹${Number(v || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
const d = (v) => v ? new Date(v).toLocaleDateString("en-IN") : "—";
const dt = (v) => v ? new Date(v).toLocaleString("en-IN") : "—";
const n = (v) => Number(v || 0);
const status = (v) => String(v || "").replaceAll("_", " ");

async function publicApi(path, options = {}) {
  const headers = { ...(options.body instanceof FormData ? {} : { "Content-Type": "application/json" }), ...(options.headers || {}) };
  const res = await fetch(`${API_URL}${path}`, { ...options, headers });
  const type = res.headers.get("content-type") || "";
  const payload = type.includes("application/json") ? await res.json() : await res.text();
  if (!res.ok) throw new Error(payload?.message || payload || `Request failed ${res.status}`);
  return payload?.data ?? payload;
}

export default function VendorPortalPage() {
  const { token } = useParams();
  const encToken = encodeURIComponent(token || "");
  const [data, setData] = useState({ vendor: {}, rfqs: [], purchaseOrders: [], complaints: [] });
  const [tab, setTab] = useState("RFQ");
  const [msg, setMsg] = useState("");
  const [busy, setBusy] = useState(false);
  const [quoteEdit, setQuoteEdit] = useState(null);
  const [poEdit, setPoEdit] = useState(null);
  const [dispatchEdit, setDispatchEdit] = useState(null);
  const [complaintEdit, setComplaintEdit] = useState(null);
  const [scan, setScan] = useState(null);

  const load = async () => {
    try { const result = await publicApi(`/purchase-ai/vendor/${encToken}/home`); setData(result || {}); }
    catch (e) { setMsg(e.message); }
  };
  useEffect(() => { load(); }, [token]);

  const scanDoc = async ({ file, documentType, scopeType, scopeId }) => {
    if (!file) return null;
    setBusy(true); setMsg("");
    try {
      const fd = new FormData(); fd.append("document", file); fd.append("documentType", documentType); fd.append("scopeType", scopeType || ""); fd.append("scopeId", scopeId || "");
      const r = await publicApi(`/purchase-ai/vendor/${encToken}/documents/extract`, { method: "POST", body: fd });
      setScan({ documentType, ...r }); setMsg(`AI scan complete using ${r.engine || "document AI"}. Please verify highlighted values.`); return r;
    } catch (e) { setMsg(e.message); return null; } finally { setBusy(false); }
  };

  const openQuote = (rfq) => {
    const mine = rfq.vendors?.[0] || {};
    setQuoteEdit({ rfq, quoteNo: mine.quoteNo || "", quoteDate: mine.quoteDate?.slice?.(0,10) || new Date().toISOString().slice(0,10), validityDate: mine.validityDate?.slice?.(0,10) || "", creditDays: mine.creditDays || data.vendor?.creditDays || 0, freightTerms: mine.freightTerms || "", expectedDispatchDate: "", expectedDeliveryDate: "", vendorRemarks: "", quotationFileIds: mine.quotationFileIds || [], aiExtractionId: "", items: (rfq.items || []).map((i) => ({ productId: i.productId, sku: i.sku, productName: i.productName, qty: i.requestedQty || i.suggestedQty || 0, unit: i.unit, rate: mine.quoteItems?.find((x)=>x.productId===i.productId)?.rate || 0, discountPct: 0, gstRate: mine.quoteItems?.find((x)=>x.productId===i.productId)?.gstRate || 0, freight: 0, deliveryDays: 0 })) });
  };
  const setQuoteItem = (pid, key, value) => setQuoteEdit((q) => ({ ...q, items: q.items.map((i) => i.productId === pid ? { ...i, [key]: value } : i) }));
  const applyQuoteScan = async (file) => {
    const r = await scanDoc({ file, documentType: "VENDOR_QUOTATION", scopeType: "RFQ", scopeId: quoteEdit?.rfq?._id }); if (!r) return;
    const vals = r.extraction?.values || {}; const scannedItems = r.extraction?.items || [];
    setQuoteEdit((q) => ({ ...q, quoteNo: vals.quoteNo || q.quoteNo, quoteDate: vals.quoteDate || q.quoteDate, validityDate: vals.validityDate || q.validityDate, creditDays: vals.creditDays || q.creditDays, freightTerms: vals.freightTerms || q.freightTerms, vendorRemarks: vals.remarks || q.vendorRemarks, quotationFileIds: [...(q.quotationFileIds || []), r.fileId], aiExtractionId: r.documentId, items: q.items.map((i) => { const match = scannedItems.find((x) => String(x.sku || "").toLowerCase() === String(i.sku || "").toLowerCase()) || scannedItems.find((x) => String(x.name || "").toLowerCase().includes(String(i.productName || "").toLowerCase().slice(0,12))); return match ? { ...i, rate: match.rate || i.rate, discountPct: match.discountPct || i.discountPct, gstRate: match.gstRate || i.gstRate } : i; }) }));
  };
  const submitQuote = async () => {
    setBusy(true); try { await publicApi(`/purchase-ai/vendor/${encToken}/rfqs/${quoteEdit.rfq._id}/quote`, { method: "POST", body: JSON.stringify(quoteEdit) }); setMsg("Quotation submitted successfully."); setQuoteEdit(null); await load(); } catch (e) { setMsg(e.message); } finally { setBusy(false); }
  };

  const openConfirm = (po) => setPoEdit({ po, accepted: true, expectedDispatchDate: po.supplierConfirmation?.expectedDispatchDate?.slice?.(0,10) || "", expectedDispatchTime: po.supplierConfirmation?.expectedDispatchTime || "", expectedArrivalDate: po.supplierConfirmation?.expectedArrivalDate?.slice?.(0,10) || "", remarks: "", items: (po.items || []).map((i) => ({ productId: i.productId, productName: i.productName, confirmedQty: i.confirmedQty || i.orderedQty })) });
  const confirmPo = async () => { setBusy(true); try { await publicApi(`/purchase-ai/vendor/${encToken}/purchase-orders/${poEdit.po._id}/confirm`, { method: "POST", body: JSON.stringify(poEdit) }); setMsg("PO confirmation sent to Purchase team."); setPoEdit(null); await load(); } catch (e) { setMsg(e.message); } finally { setBusy(false); } };

  const openDispatch = (po) => setDispatchEdit({ po, invoiceNo: "", invoiceDate: new Date().toISOString().slice(0,10), invoiceAmount: 0, invoiceFileIds: [], lrNo: "", lrDate: new Date().toISOString().slice(0,10), lrFileIds: [], transporterName: "", vehicleNo: "", fromLocation: "", destination: "", packages: 0, weight: 0, freight: 0, freightMode: "TO PAY", dispatchDate: new Date().toISOString().slice(0,10), dispatchTime: "", expectedArrival: "", aiExtractionIds: [], items: (po.items || []).map((i) => ({ productId: i.productId, productName: i.productName, qty: Math.max(0, n(i.confirmedQty || i.orderedQty) - n(i.dispatchedQty)) })) });
  const scanInvoice = async (file) => { const r = await scanDoc({ file, documentType: "SUPPLIER_INVOICE", scopeType: "PURCHASE_ORDER", scopeId: dispatchEdit?.po?._id }); if (!r) return; const v = r.extraction?.values || {}; setDispatchEdit((x) => ({ ...x, invoiceNo: v.invoiceNo || x.invoiceNo, invoiceDate: v.date || x.invoiceDate, invoiceAmount: v.invoiceValue || x.invoiceAmount, packages: v.packages || x.packages, invoiceFileIds: [...x.invoiceFileIds, r.fileId], aiExtractionIds: [...x.aiExtractionIds, r.documentId] })); };
  const scanLr = async (file) => { const r = await scanDoc({ file, documentType: "LR_COPY", scopeType: "PURCHASE_ORDER", scopeId: dispatchEdit?.po?._id }); if (!r) return; const v = r.extraction?.values || {}; setDispatchEdit((x) => ({ ...x, transporterName: v.transporterName || x.transporterName, lrNo: v.lrNo || x.lrNo, lrDate: v.lrDate || x.lrDate, fromLocation: v.fromLocation || x.fromLocation, destination: v.destination || x.destination, packages: v.packages || x.packages, weight: v.weight || x.weight, freight: v.freight || x.freight, freightMode: v.freightMode || x.freightMode, vehicleNo: v.vehicleNo || x.vehicleNo, expectedArrival: v.expectedArrival || x.expectedArrival, lrFileIds: [...x.lrFileIds, r.fileId], aiExtractionIds: [...x.aiExtractionIds, r.documentId] })); };
  const submitDispatch = async () => { setBusy(true); try { await publicApi(`/purchase-ai/vendor/${encToken}/purchase-orders/${dispatchEdit.po._id}/dispatch`, { method: "POST", body: JSON.stringify(dispatchEdit) }); setMsg("Dispatch submitted. Warehouse has been notified in Incoming Material."); setDispatchEdit(null); await load(); } catch (e) { setMsg(e.message); } finally { setBusy(false); } };

  const openComplaint = (c) => setComplaintEdit({ complaint: c, action: "REPLACE", remarks: "", promisedDate: "", responseFileIds: [], creditNote: null });
  const scanCreditNote = async (file) => { const r = await scanDoc({ file, documentType: "SUPPLIER_CREDIT_NOTE", scopeType: "COMPLAINT", scopeId: complaintEdit?.complaint?._id }); if (!r) return; const v = r.extraction?.values || {}; setComplaintEdit((x) => ({ ...x, action: "CREDIT_NOTE", creditNote: { creditNoteNo: v.creditNoteNo || "", date: v.date || "", taxableValue: v.taxableValue || 0, tax: v.tax || 0, total: v.total || 0, fileIds: [r.fileId], aiExtractionId: r.documentId } })); };
  const submitComplaint = async () => { setBusy(true); try { await publicApi(`/purchase-ai/vendor/${encToken}/complaints/${complaintEdit.complaint._id}/respond`, { method: "POST", body: JSON.stringify(complaintEdit) }); setMsg("Complaint response submitted."); setComplaintEdit(null); await load(); } catch (e) { setMsg(e.message); } finally { setBusy(false); } };

  const openPayments = useMemo(() => (data.purchaseOrders || []).filter((p) => ["ACCOUNTING_PENDING","ACCOUNTED"].includes(p.status) || p.paymentStatus !== "NOT_DUE"), [data.purchaseOrders]);
  const fileUrl = (fileId) => `${API_URL}/purchase-ai/vendor/${encToken}/files/${encodeURIComponent(fileId)}`;

  return <div className="purchase-ai" style={{maxWidth:1250,margin:"0 auto"}}>
    <div className="pa-head"><div className="pa-title"><BrainCircuit size={25}/><div><h1>Vendor Collaboration Portal</h1><div className="pa-muted">{data.vendor?.name || "Supplier"} • RFQ, PO, dispatch, complaints and payment tracking</div></div></div><button className="pa-btn" onClick={load}><RefreshCw size={14}/>Refresh</button></div>
    {msg && <div className="pa-msg">{msg}</div>}
    <div className="pa-tabs"><button className={`pa-tab ${tab==="RFQ"?"active":""}`} onClick={()=>setTab("RFQ")}><FileText size={13}/> RFQ</button><button className={`pa-tab ${tab==="PO"?"active":""}`} onClick={()=>setTab("PO")}><CheckCircle2 size={13}/> Orders</button><button className={`pa-tab ${tab==="DISPATCH"?"active":""}`} onClick={()=>setTab("DISPATCH")}><Truck size={13}/> Dispatch</button><button className={`pa-tab ${tab==="COMPLAINTS"?"active":""}`} onClick={()=>setTab("COMPLAINTS")}><AlertTriangle size={13}/> Complaints</button><button className={`pa-tab ${tab==="PAYMENTS"?"active":""}`} onClick={()=>setTab("PAYMENTS")}><IndianRupee size={13}/> Payments</button></div>

    {tab==="RFQ" && <div className="pa-stack">{(data.rfqs||[]).map((r)=>{const me=r.vendors?.[0]||{};return <div className="pa-panel" key={r._id}><div className="pa-head"><div><b>{r.rfqNo}</b> <span className="pa-badge blue">{status(me.status)}</span><div className="pa-muted">Required {d(r.requiredByDate)} • {r.deliveryLocation||"Delivery location as PO"}</div></div><button className="pa-btn primary" onClick={()=>openQuote(r)}>{me.status==="SUBMITTED"?"Revise Quote":"Submit Quote"}</button></div><div className="pa-table-wrap"><table className="pa-table"><thead><tr><th>Product</th><th>Qty</th><th>Unit</th></tr></thead><tbody>{(r.items||[]).map((i)=><tr key={i.productId}><td>{i.productName}</td><td>{i.requestedQty||i.suggestedQty}</td><td>{i.unit}</td></tr>)}</tbody></table></div></div>})}{!(data.rfqs||[]).length&&<div className="pa-panel">No open quotation requests.</div>}</div>}

    {tab==="PO" && <div className="pa-stack">{(data.purchaseOrders||[]).map((po)=><div className="pa-panel" key={po._id}><div className="pa-head"><div><b>{po.poNo}</b> <span className="pa-badge blue">{status(po.status)}</span><div className="pa-muted">PO value {money(po.grandTotal)} • Required {d(po.requiredByDate)}</div></div><div className="pa-actions">{["PO_SENT","SUPPLIER_CHANGE_REQUESTED"].includes(po.status)&&<button className="pa-btn good" onClick={()=>openConfirm(po)}>Confirm / Request Change</button>}<button className="pa-btn" onClick={()=>openDispatch(po)}><Truck size={13}/>Dispatch</button></div></div><div className="pa-table-wrap"><table className="pa-table"><thead><tr><th>Product</th><th>Ordered</th><th>Confirmed</th><th>Rate</th></tr></thead><tbody>{(po.items||[]).map((i)=><tr key={i.productId}><td>{i.productName}</td><td>{i.orderedQty}</td><td>{i.confirmedQty||0}</td><td>{money(i.rate)}</td></tr>)}</tbody></table></div></div>)}</div>}

    {tab==="DISPATCH" && <div className="pa-stack">{(data.purchaseOrders||[]).filter((p)=>(p.shipments||[]).length).map((po)=><div className="pa-panel" key={po._id}><b>{po.poNo}</b>{(po.shipments||[]).map((s)=><div className="pa-insight" style={{marginTop:8}} key={s._id}><b>{s.lrNo||s.shipmentNo}</b> • {s.transporterName||"Transporter"} • {s.packages||0} packages • dispatched {d(s.dispatchDate)} • expected {dt(s.expectedArrival)}</div>)}</div>)}{!(data.purchaseOrders||[]).some((p)=>(p.shipments||[]).length)&&<div className="pa-panel">No dispatches submitted yet.</div>}</div>}

    {tab==="COMPLAINTS" && <div className="pa-stack">{(data.complaints||[]).map((c)=><div className="pa-panel" key={c._id}><div className="pa-head"><div><b>{c.complaintNo} • {c.poNo}</b><div className="pa-muted">{status(c.status)} • {dt(c.createdAt)}</div></div>{c.status!=="CLOSED"&&<button className="pa-btn warn" onClick={()=>openComplaint(c)}>Respond</button>}</div><p>{c.description}</p><div className="pa-table-wrap"><table className="pa-table"><thead><tr><th>Product</th><th>Received</th><th>Damaged</th><th>Rejected</th><th>Short</th></tr></thead><tbody>{(c.items||[]).map((i)=><tr key={i.productId}><td>{i.productName}</td><td>{i.receivedQty}</td><td>{i.damagedQty}</td><td>{i.rejectedQty}</td><td>{i.shortQty}</td></tr>)}</tbody></table></div><div className="pa-inline" style={{marginTop:8}}>{[...(c.evidenceFileIds||[]),...(c.items||[]).flatMap((i)=>i.evidenceFileIds||[])].filter((x,i,a)=>a.indexOf(x)===i).map((fid)=><a key={fid} href={fileUrl(fid)} target="_blank" rel="noreferrer"><img className="pa-photo" src={fileUrl(fid)} alt="QC evidence"/></a>)}</div>{c.vendorResponse?.respondedAt&&<div className="pa-insight">Your response: <b>{status(c.vendorResponse.action)}</b> — {c.vendorResponse.remarks}</div>}</div>)}{!(data.complaints||[]).length&&<div className="pa-panel">No complaints or QC claims.</div>}</div>}

    {tab==="PAYMENTS" && <div className="pa-table-wrap"><table className="pa-table"><thead><tr><th>PO</th><th>Amount</th><th>Accounting</th><th>Payment</th><th>Due Date</th><th>Reference</th></tr></thead><tbody>{openPayments.map((p)=><tr key={p._id}><td>{p.poNo}</td><td>{money(p.grandTotal)}</td><td>{status(p.accountingStatus)}</td><td>{status(p.paymentStatus)}</td><td>{d(p.paymentDueDate)}</td><td>{p.paymentReference||"—"}</td></tr>)}{!openPayments.length&&<tr><td colSpan="6">No payment status is available yet.</td></tr>}</tbody></table></div>}

    {quoteEdit && <div className="pa-modal-backdrop"><div className="pa-modal"><div className="pa-modal-head"><div><b>Quotation • {quoteEdit.rfq.rfqNo}</b><div className="pa-muted">Upload your quotation for AI scan or enter rates manually.</div></div><button className="pa-btn" onClick={()=>setQuoteEdit(null)}>Close</button></div><div className="pa-doc"><label className="pa-btn"><Upload size={13}/>AI Scan Quotation<input hidden type="file" accept="image/*,application/pdf" onChange={(e)=>applyQuoteScan(e.target.files?.[0])}/></label></div><div className="pa-form-grid" style={{marginTop:10}}><label>Quote No<input className="pa-input" value={quoteEdit.quoteNo} onChange={(e)=>setQuoteEdit({...quoteEdit,quoteNo:e.target.value})}/></label><label>Quote Date<input className="pa-input" type="date" value={quoteEdit.quoteDate} onChange={(e)=>setQuoteEdit({...quoteEdit,quoteDate:e.target.value})}/></label><label>Credit Days<input className="pa-input" type="number" value={quoteEdit.creditDays} onChange={(e)=>setQuoteEdit({...quoteEdit,creditDays:e.target.value})}/></label><label>Freight Terms<input className="pa-input" value={quoteEdit.freightTerms} onChange={(e)=>setQuoteEdit({...quoteEdit,freightTerms:e.target.value})}/></label></div><div className="pa-table-wrap" style={{marginTop:10}}><table className="pa-table"><thead><tr><th>Product</th><th>Qty</th><th>Rate</th><th>Disc %</th><th>GST %</th><th>Freight</th><th>Delivery Days</th></tr></thead><tbody>{quoteEdit.items.map((i)=><tr key={i.productId}><td>{i.productName}</td><td>{i.qty}</td>{["rate","discountPct","gstRate","freight","deliveryDays"].map((k)=><td key={k}><input className="pa-input" type="number" value={i[k]} onChange={(e)=>setQuoteItem(i.productId,k,e.target.value)}/></td>)}</tr>)}</tbody></table></div><div className="pa-actions" style={{marginTop:10,justifyContent:"flex-end"}}><button className="pa-btn primary" disabled={busy} onClick={submitQuote}><Send size={13}/>Submit Quotation</button></div></div></div>}

    {poEdit && <div className="pa-modal-backdrop"><div className="pa-modal small"><div className="pa-modal-head"><b>Confirm {poEdit.po.poNo}</b><button className="pa-btn" onClick={()=>setPoEdit(null)}>Close</button></div><div className="pa-form-grid"><label>Expected Dispatch<input className="pa-input" type="date" value={poEdit.expectedDispatchDate} onChange={(e)=>setPoEdit({...poEdit,expectedDispatchDate:e.target.value})}/></label><label>Dispatch Time<input className="pa-input" type="time" value={poEdit.expectedDispatchTime} onChange={(e)=>setPoEdit({...poEdit,expectedDispatchTime:e.target.value})}/></label><label>Expected Arrival<input className="pa-input" type="date" value={poEdit.expectedArrivalDate} onChange={(e)=>setPoEdit({...poEdit,expectedArrivalDate:e.target.value})}/></label></div><label>Remarks<textarea className="pa-textarea" value={poEdit.remarks} onChange={(e)=>setPoEdit({...poEdit,remarks:e.target.value})}/></label><div className="pa-actions"><button className="pa-btn warn" onClick={()=>setPoEdit({...poEdit,accepted:false})}>Request Change</button><button className="pa-btn good" onClick={()=>setPoEdit({...poEdit,accepted:true})}>Accept</button><button className="pa-btn primary" onClick={confirmPo}>Submit</button></div></div></div>}

    {dispatchEdit && <div className="pa-modal-backdrop"><div className="pa-modal"><div className="pa-modal-head"><div><b>Dispatch • {dispatchEdit.po.poNo}</b><div className="pa-muted">AI can read both supplier invoice and LR/Bilty.</div></div><button className="pa-btn" onClick={()=>setDispatchEdit(null)}>Close</button></div><div className="pa-grid"><div className="pa-doc"><b>Supplier Invoice</b><div><label className="pa-btn"><BrainCircuit size={13}/>AI Scan Bill<input hidden type="file" accept="image/*,application/pdf" onChange={(e)=>scanInvoice(e.target.files?.[0])}/></label></div></div><div className="pa-doc"><b>LR / Bilty / CN</b><div><label className="pa-btn"><BrainCircuit size={13}/>AI Scan LR<input hidden type="file" accept="image/*,application/pdf" onChange={(e)=>scanLr(e.target.files?.[0])}/></label></div></div></div><div className="pa-form-grid" style={{marginTop:10}}>{[["invoiceNo","Invoice No"],["invoiceDate","Invoice Date","date"],["invoiceAmount","Invoice Amount","number"],["lrNo","LR No"],["lrDate","LR Date","date"],["transporterName","Transporter"],["vehicleNo","Vehicle No"],["packages","Packages","number"],["weight","Weight","number"],["freight","Freight","number"],["freightMode","Freight Mode"],["expectedArrival","Expected Arrival","date"]].map(([k,l,t])=><label key={k}>{l}<input className="pa-input" type={t||"text"} value={dispatchEdit[k]??""} onChange={(e)=>setDispatchEdit({...dispatchEdit,[k]:e.target.value})}/></label>)}</div><div className="pa-actions" style={{marginTop:10,justifyContent:"flex-end"}}><button className="pa-btn primary" disabled={busy} onClick={submitDispatch}><Truck size={13}/>Submit Dispatch</button></div></div></div>}

    {complaintEdit && <div className="pa-modal-backdrop"><div className="pa-modal small"><div className="pa-modal-head"><b>Respond • {complaintEdit.complaint.complaintNo}</b><button className="pa-btn" onClick={()=>setComplaintEdit(null)}>Close</button></div><label>Action<select className="pa-select" value={complaintEdit.action} onChange={(e)=>setComplaintEdit({...complaintEdit,action:e.target.value})}><option value="REPLACE">Replace Material</option><option value="CREDIT_NOTE">Issue Credit Note</option><option value="SEND_SHORT_QTY">Send Short Quantity</option><option value="ACCEPT_CLAIM">Accept Claim</option><option value="DISPUTE">Dispute / Need Clarification</option></select></label><label>Promised Date<input className="pa-input" type="date" value={complaintEdit.promisedDate} onChange={(e)=>setComplaintEdit({...complaintEdit,promisedDate:e.target.value})}/></label><label>Remarks<textarea className="pa-textarea" value={complaintEdit.remarks} onChange={(e)=>setComplaintEdit({...complaintEdit,remarks:e.target.value})}/></label><div className="pa-doc"><label className="pa-btn"><BrainCircuit size={13}/>AI Scan Credit Note<input hidden type="file" accept="image/*,application/pdf" onChange={(e)=>scanCreditNote(e.target.files?.[0])}/></label>{complaintEdit.creditNote&&<div className="pa-muted">Detected {complaintEdit.creditNote.creditNoteNo} • {money(complaintEdit.creditNote.total)}</div>}</div><div className="pa-actions" style={{marginTop:10,justifyContent:"flex-end"}}><button className="pa-btn primary" onClick={submitComplaint}><Send size={13}/>Submit Response</button></div></div></div>}

    {scan && <div className="pa-panel"><b>Last AI Scan: {scan.documentType}</b><div className="pa-muted">Document {scan.documentId} • engine {scan.engine||"AI"}. Values were applied to the active form where possible.</div></div>}
  </div>;
}
