import {
  LayoutDashboard,
  Users,
  UserRoundCog,
  MapPinned,
  Truck,
  Package,
  Barcode,
  ShoppingCart,
  ShoppingBasket,
  Warehouse,
  Landmark,
  BadgeIndianRupee,
  ReceiptIndianRupee,
  Target,
  Activity,
  HeartPulse,
  FileBarChart,
  Building2,
  Settings,
  ShieldCheck,
  BrainCircuit,
  Database,
  Factory,
  ClipboardList,
  Boxes,
  Wrench,
  BadgeCheck,
  CalendarDays,
  Clock3,
  WalletCards,
  BriefcaseBusiness,
  UserPlus,
  IndianRupee,
  Banknote,
  ScanLine,
  CloudCog,
  FileLock2,
  CircleDollarSign,
  BookOpenCheck,
  Scale,
  Percent,
  RotateCcw,
  HandCoins,
  Network,
  Gauge,
  ListChecks,
  ContactRound,
  Route,
  Layers3,
  FileText,
  GitCompareArrows,
} from "lucide-react";

export const apps = [
  { key: "master", label: "MASTER", icon: ShieldCheck, accent: "violet" },
  { key: "dms", label: "DMS", icon: Building2, accent: "indigo" },
  // HR and Production are intentionally disabled for now. Their source
  // definitions remain below so they can be re-enabled later without loss.
];

const p = (path, label, icon, description, kind = "list") => ({
  path,
  label,
  icon,
  description,
  kind,
});
export const nav = {
  master: [
    {
      group: "Platform",
      items: [
        p(
          "/master/dashboard",
          "Master Dashboard",
          LayoutDashboard,
          "Plans, tenants, storage, verification and platform health",
          "dashboard",
        ),
        p(
          "/master/superadmins",
          "Superadmins / Companies",
          Building2,
          "Create company tenants, assign plans and first Superadmin login",
          "superadmins",
        ),
        p(
          "/master/plans",
          "Plans",
          Layers3,
          "DMS plans, permission groups, add-ons and limits",
          "plans",
        ),
        p(
          "/master/departments",
          "Department Management",
          Building2,
          "MASTER-only fixed Department catalogue: name, description and active/inactive status",
          "master-departments",
        ),
        p(
          "/master/groups",
          "Groups",
          Layers3,
          "Independent MASTER group management",
          "groups",
        ),
        p(
          "/master/designations",
          "Designation Security",
          BadgeCheck,
          "MASTER designation field access and workflow security templates",
          "designation-security",
        ),
        p(
          "/master/branding",
          "Branding",
          BadgeCheck,
          "MASTER logo, generated-document slogan and print rules",
          "branding",
        ),
      ],
    },
    {
      group: "Global data",
      items: [
        p(
          "/master/pincodes",
          "Pincode & Geography",
          MapPinned,
          "Bulk upload, hierarchical selection, bulk edit/delete of pincode geography",
          "pincodes",
        ),
        p(
          "/master/hsn",
          "HSN / SAC / GST",
          Percent,
          "Global statutory HSN/SAC and tax-rate registry",
        ),
        p(
          "/master/ifsc",
          "IFSC / Bank Branches",
          Landmark,
          "Global IFSC bank-branch database for automatic bank-detail lookup",
          "ifsc-master",
        ),
        p(
          "/master/units",
          "Units / UQC",
          Boxes,
          "Global unit and GST UQC master with bulk management",
        ),
        p(
          "/master/customers",
          "Global Customer Registry",
          ContactRound,
          "GSTIN/PAN/Aadhaar identity, contacts and global health",
        ),
        p(
          "/master/transporters",
          "Global Transporter Registry",
          Truck,
          "All-India transporter directory with bulk import and company lookup",
          "transporter-master",
        ),
        p(
          "/master/barcodes",
          "Barcode & GTIN Center",
          Barcode,
          "Central online barcode/GTIN database and allocation",
        ),
      ],
    },
    {
      group: "Core control",
      items: [
        p(
          "/master/accounts",
          "Accounting Framework",
          Scale,
          "Locked Tally-style groups, system ledgers, report/CMA mappings",
        ),
        p(
          "/master/gst-api",
          "Statutory API Services",
          GitCompareArrows,
          "GSTIN search, return status, GSTR reconciliation adapters",
          "gst-api",
        ),
        p(
          "/master/storage",
          "NAS + Cloud Storage",
          CloudCog,
          "Primary NAS, backup, quotas, file service and health",
        ),
        p(
          "/master/audit",
          "Platform Audit",
          FileLock2,
          "Immutable system audit and security events",
        ),
      ],
    },
  ],
  dms: [
    {
      group: "Overview",
      items: [
        p(
          "/dms/dashboard",
          "AI Company Health",
          LayoutDashboard,
          "Real-time sales, profit, expenses, targets, stock, customers and AI actions",
          "dashboard",
        ),
        p(
          "/dms/health",
          "Company Health",
          HeartPulse,
          "Health score, drilldowns and risk/opportunity signals",
        ),
        p(
          "/dms/targets",
          "Sales Target & Achievement",
          Target,
          "Yearly parent target, customer allocation, monthly auto-generation and visits",
          "target",
        ),
      ],
    },
    {
      group: "CRM & Parties",
      items: [
        p(
          "/dms/leads",
          "Sales Leads",
          UserPlus,
          "Bulk lead upload, pincode assignment, actions and conversions",
          "leads",
        ),
        p(
          "/dms/customers",
          "Customers",
          Users,
          "Global identity + company commercial profile + KYC + approval",
          "customers",
        ),
        p(
          "/dms/customer-grades",
          "Customer Grades",
          BadgeCheck,
          "Grade and grade-discount master used by sales invoices and price lists",
          "customer-grades",
        ),
        p(
          "/dms/transporters",
          "Transporters",
          Truck,
          "One transporter, many stations, many contacts",
          "transporters",
        ),
        p(
          "/dms/visits",
          "Visits",
          Route,
          "GPS and optional internal-OTP verified salesperson visits",
        ),
      ],
    },
    {
      group: "Sales",
      items: [
        p(
          "/dms/quotation",
          "Quotation",
          FileText,
          "Quotations with price-health validation",
        ),
        p(
          "/dms/sales-orders",
          "Sales Orders",
          ShoppingCart,
          "Customer health, credit and approval aware sales orders",
        ),
        p(
          "/dms/dispatch",
          "Dispatch",
          Truck,
          "Picking, packing and transporter handover",
        ),
        p(
          "/dms/sales-invoices",
          "Sales Invoices",
          ReceiptIndianRupee,
          "Invoice generation with accounting and GST snapshot",
          "sales-invoices",
        ),
        p(
          "/dms/sales-returns",
          "Sales Return",
          RotateCcw,
          "Controlled goods return and reversal workflow",
        ),
        p(
          "/dms/credit-notes",
          "Credit Notes",
          HandCoins,
          "Credit note workflow and accounting",
        ),
      ],
    },
    {
      group: "Purchase",
      items: [
        p(
          "/dms/purchase-request",
          "Purchase Request",
          ClipboardList,
          "Demand and replenishment requests",
        ),
        p(
          "/dms/rfq",
          "RFQ",
          BriefcaseBusiness,
          "Supplier requests and comparison",
        ),
        p(
          "/dms/purchase-orders",
          "Purchase Orders",
          ShoppingBasket,
          "Purchase order workflow",
        ),
        p("/dms/grn", "Goods Receipt", Boxes, "GRN and receiving"),
        p(
          "/dms/purchase-invoices",
          "Purchase Invoices",
          ReceiptIndianRupee,
          "DMS-style purchase invoice with average purchase and landed-cost update",
          "purchase-invoices",
        ),
        p(
          "/dms/purchase-returns",
          "Purchase Returns",
          RotateCcw,
          "Purchase return and debit note workflow",
        ),
      ],
    },
    {
      group: "Products & Stock",
      items: [
        p(
          "/dms/products",
          "Products",
          Package,
          "DMS product master with pack quantity, purchase averages, landed, MRP and stock",
          "products",
        ),
        p(
          "/dms/product-categories",
          "Categories & Sub-Categories",
          Layers3,
          "Company product category/sub-category master",
          "product-categories",
        ),
        p(
          "/dms/units",
          "Units / UQC",
          Boxes,
          "Company unit master used in product, stock, sales and purchase",
          "dms-units",
        ),
        p(
          "/dms/price-list",
          "Price List",
          BadgeIndianRupee,
          "Customer-grade price lists generated from MRP with product overrides",
          "price-list",
        ),
        p(
          "/dms/price-management",
          "Price Management",
          BadgeIndianRupee,
          "Dynamic minimum margin and red/blue/green profit bands",
          "pricing",
        ),
        p(
          "/dms/stock",
          "Current Stock",
          Boxes,
          "Real-time stock and valuation",
        ),
        p(
          "/dms/warehouses",
          "Warehouses",
          Warehouse,
          "Warehouse master and stock by location",
        ),
        p(
          "/dms/stock-transfer",
          "Stock Transfer",
          Network,
          "Warehouse transfers",
        ),
        p(
          "/dms/closing-stock",
          "Closing Stock",
          ClipboardList,
          "FY closing and opening stock carry-forward",
        ),
        p(
          "/dms/stock-ageing",
          "Stock Ageing",
          Clock3,
          "Slow/dead stock and ageing",
        ),
      ],
    },
    {
      group: "Money & Accounts",
      items: [
        p(
          "/dms/banking",
          "Bank Transactions",
          Landmark,
          "Receipt, payment and bank statement posting in one reviewed workflow",
          "bank-transactions",
        ),
        p(
          "/dms/bank-accounts",
          "Bank Accounts",
          Landmark,
          "Bank master and financial-year opening balances",
          "bank-accounts",
        ),
        p(
          "/dms/expenses",
          "Expense Management",
          CircleDollarSign,
          "Actual, accrued and allocated expenses",
        ),
        p("/dms/ledger", "Ledger", BookOpenCheck, "Party/account ledgers"),
        p(
          "/dms/trial-balance",
          "Trial Balance",
          Scale,
          "Trial balance from central accounting engine",
        ),
        p(
          "/dms/trading",
          "Trading Account",
          FileBarChart,
          "Trading and gross-profit report",
        ),
        p(
          "/dms/pnl",
          "Profit & Loss",
          FileBarChart,
          "Official and management P&L",
        ),
        p(
          "/dms/balance-sheet",
          "Balance Sheet",
          FileBarChart,
          "Final/provisional balance sheet",
        ),
        p(
          "/dms/cma",
          "CMA & Finance",
          Gauge,
          "CMA, working capital, ratios and projections",
        ),
      ],
    },
    {
      group: "GST & Compliance",
      items: [
        p(
          "/dms/gst-dashboard",
          "GST Health",
          BadgeCheck,
          "GST compliance and exception health",
        ),
        p(
          "/dms/gst-reports",
          "GST Reports",
          FileBarChart,
          "Old-DMS GST report suite: GSTR 1, GSTR 2B, GSTR 3B, HSN Wise, GST Input/Output and Tax",
          "gst-reports",
        ),
        p(
          "/dms/gstr1",
          "GSTR-1",
          FileText,
          "Old-DMS GSTR-1 with B2B/B2CL/B2CS and CDNR/CDNUR",
          "gst-reports",
        ),
        p(
          "/dms/gstr2b",
          "GSTR-2B",
          GitCompareArrows,
          "Old-DMS purchase/ITC report",
          "gst-reports",
        ),
        p(
          "/dms/gstr3b",
          "GSTR-3B",
          GitCompareArrows,
          "Old-DMS GSTR-3B summary",
          "gst-reports",
        ),
        p(
          "/dms/hsn-wise-report",
          "HSN Wise",
          Barcode,
          "Old-DMS HSN-wise GST report and reconciliation",
          "gst-reports",
        ),
        p(
          "/dms/gst-input-output",
          "GST Input / Output",
          Scale,
          "Old-DMS GST input/output report",
          "gst-reports",
        ),
        p(
          "/dms/tax-report",
          "Tax Report",
          IndianRupee,
          "Old-DMS total tax input, output and balance",
          "gst-reports",
        ),
        p(
          "/dms/gstr9",
          "GSTR-9",
          FileText,
          "Annual reconciliation and return support",
        ),
      ],
    },
    {
      group: "Administration",
      items: [
        p(
          "/dms/roles",
          "Role Management",
          ShieldCheck,
          "Create tenant Roles and assign only permissions available to this Superadmin",
          "roles",
        ),
        p(
          "/dms/department-role-assignment",
          "Department Role Assignment",
          Network,
          "Add Superadmin Roles to fixed MASTER Departments and set dynamic ranks",
          "department-role-assignment",
        ),
        p(
          "/dms/users",
          "Users & Pincode Assignment",
          UserRoundCog,
          "Create users and manage pincode-based customer/lead assignment",
          "users",
        ),
        p(
          "/dms/sales-pincode-allotment",
          "Sales Pincode Allotment",
          MapPinned,
          "Sales Head coverage and Sales Person wise pincode allotment",
          "sales-pincode-allotment",
        ),
        p(
          "/dms/branches",
          "Branch Management",
          Building2,
          "Create branches within the number allowed by the company plan",
          "branches",
        ),
        p(
          "/dms/customer-approvals",
          "Customer Approvals",
          UserPlus,
          "Admin/Accounts approval inbox for new customers and credit terms",
          "customer-approvals",
        ),
        p(
          "/dms/company-settings",
          "Company & Stakeholders",
          Building2,
          "Legal constitution, proprietor/partners/directors and generated accounting ledgers",
          "company-settings",
        ),
      ],
    },
    {
      group: "AI & Forms",
      items: [
        p(
          "/dms/scan-forms",
          "AI Scan & QR Forms",
          ScanLine,
          "Print QR-coded forms and use AI Scan & Fill across DMS",
          "scan-forms",
        ),
        p(
          "/dms/legacy-migration",
          "Previous DMS → V2",
          Database,
          "Upload Previous DMS database exports and preserve old IDs",
          "legacy-migration",
        ),
      ],
    },
    {
      group: "Other",
      items: [
        p(
          "/dms/family",
          "Family & Individual Accounts",
          Users,
          "Bank-statement-first personal/family accounting",
        ),
        p(
          "/dms/reports",
          "All DMS Reports",
          FileBarChart,
          "Central report catalogue with PDF/Excel/Print",
          "reports",
        ),
        p(
          "/dms/settings",
          "DMS Settings",
          Settings,
          "Company-specific DMS settings",
        ),
      ],
    },
  ],
  hr: [
    {
      group: "HR Overview",
      items: [
        p(
          "/hr/dashboard",
          "HR Dashboard",
          LayoutDashboard,
          "Headcount, attendance, leave, payroll and AI alerts",
          "dashboard",
        ),
        p(
          "/hr/employees",
          "Employees",
          Users,
          "Employee profile, reporting, documents and ledger",
          "employees",
        ),
        p(
          "/hr/users",
          "Users & Access",
          UserRoundCog,
          "Create logins, assign role and Reports To",
          "users",
        ),
      ],
    },
    {
      group: "Organisation",
      items: [
        p(
          "/hr/departments",
          "Departments",
          Building2,
          "Department master and ownership",
        ),
        p(
          "/hr/designations",
          "Designations",
          BadgeCheck,
          "Designation and reporting level master",
        ),
        p("/hr/teams", "Teams", Users, "Operational teams and managers"),
        p(
          "/hr/hierarchy",
          "Hierarchy",
          Network,
          "Automatic organisation tree generated from Reports To",
          "hierarchy",
        ),
        p(
          "/hr/roles",
          "Roles & Permissions",
          ShieldCheck,
          "Company roles and permissions",
          "roles",
        ),
      ],
    },
    {
      group: "Time & Leave",
      items: [
        p(
          "/hr/attendance",
          "Attendance",
          Clock3,
          "Daily/monthly attendance and geo verification",
        ),
        p("/hr/shifts", "Shifts", CalendarDays, "Shift definitions and rules"),
        p(
          "/hr/leave",
          "Leave",
          CalendarDays,
          "Requests, approvals and balances",
        ),
        p("/hr/holidays", "Holidays", CalendarDays, "Holiday calendar"),
      ],
    },
    {
      group: "Payroll & Money",
      items: [
        p(
          "/hr/payroll",
          "Payroll",
          IndianRupee,
          "Salary calculation, deductions and payslips",
        ),
        p(
          "/hr/loans",
          "Loans & Advances",
          HandCoins,
          "Employee loans, advances, EMI and interest",
        ),
        p(
          "/hr/expenses",
          "Employee Expenses",
          WalletCards,
          "Claims, approvals and reimbursements",
        ),
        p(
          "/hr/ledger",
          "Employee Ledger",
          BookOpenCheck,
          "Salary, incentive, loan and reimbursement ledger",
        ),
      ],
    },
    {
      group: "People",
      items: [
        p(
          "/hr/recruitment",
          "Recruitment",
          UserPlus,
          "Job openings, applications, screening and joining",
          "recruitment",
        ),
        p(
          "/hr/performance",
          "Performance",
          Activity,
          "Performance and target-linked review",
        ),
        p(
          "/hr/documents",
          "Documents",
          FileText,
          "Employee documents stored through file service",
        ),
        p(
          "/hr/reports",
          "HR Reports",
          FileBarChart,
          "Attendance, payroll, leave, employee and expense reports",
          "reports",
        ),
      ],
    },
  ],
  production: [
    {
      group: "Production Overview",
      items: [
        p(
          "/production/dashboard",
          "Production Dashboard",
          LayoutDashboard,
          "Plan vs actual, efficiency, WIP, quality and machine health",
          "dashboard",
        ),
        p(
          "/production/planning",
          "Planning",
          ClipboardList,
          "Demand, material, machine and labour planning",
        ),
        p(
          "/production/bom",
          "Bill of Materials",
          Layers3,
          "BOM and component definition",
        ),
        p(
          "/production/work-orders",
          "Work Orders",
          ClipboardList,
          "Product, quantity, machine, shift and schedule",
        ),
      ],
    },
    {
      group: "Execution",
      items: [
        p(
          "/production/raw-material",
          "Raw Material",
          Boxes,
          "Issue and material consumption",
        ),
        p("/production/wip", "WIP", Network, "Work-in-progress tracking"),
        p(
          "/production/execution",
          "Production",
          Factory,
          "Start, pause, complete, quantity and batches",
        ),
        p(
          "/production/finished-goods",
          "Finished Goods",
          Package,
          "Finished goods receipt and barcode label integration",
        ),
        p(
          "/production/scrap",
          "Scrap",
          RotateCcw,
          "Reusable, rejected and saleable scrap",
        ),
      ],
    },
    {
      group: "Control",
      items: [
        p(
          "/production/quality",
          "Quality",
          BadgeCheck,
          "Incoming, in-process and finished-goods QC",
        ),
        p(
          "/production/machines",
          "Machines",
          Wrench,
          "Capacity, runtime, downtime and efficiency",
        ),
        p(
          "/production/maintenance",
          "Maintenance",
          Wrench,
          "Preventive maintenance and breakdown",
        ),
        p(
          "/production/reports",
          "Production Reports",
          FileBarChart,
          "Plan, efficiency, WIP, QC, scrap and downtime reports",
          "reports",
        ),
      ],
    },
  ],
};

// Only MASTER and DMS are routed. HR/Production source definitions above are
// intentionally dormant/commented-out at the routing layer.
const enabledRouteApps = ["master", "dms"];
export const allPages = enabledRouteApps.flatMap((app) =>
  (nav[app] || []).flatMap((group) =>
    group.items.map((item) => ({ ...item, app, group: group.group })),
  ),
);
export const pageByPath = Object.fromEntries(
  allPages.map((page) => [page.path, page]),
);
